<?php
get_header('bare');

function zm_home_website_visual(): void { ?>
<div class="zmh-visual"><p class="zmh-caption">Przykładowa strona dla branży beauty · demonstracja</p><div class="zmh-website zmh-glass"><div class="zmh-mini-nav"><b>✳ Natura Studio</b><span>O nas&nbsp;&nbsp; Oferta&nbsp;&nbsp; Kontakt</span></div><div class="zmh-site-interior"><span>CHWILA DLA SIEBIE</span><h3>Spokojniej.<br>Bliżej siebie.</h3><p>Pielęgnacja. Relaks. Naturalne piękno.</p><span class="zmh-sample-button">Poznaj zabiegi ↗</span></div></div></div>
<?php }
function zm_home_form_visual(): void { ?>
<div class="zmh-visual zmh-form-visual"><div class="zmh-sample-form zmh-glass" aria-label="Ilustracja formularza dla firmy klienta"><p class="zmh-caption">PRZYKŁADOWY FORMULARZ USŁUGOWY</p><h3>Zapytaj o usługę</h3><div><span>Usługa</span><span>Wybierz usługę ⌄</span></div><div><span>Termin</span><span>Preferowany termin ▦</span></div><div><span>Opis</span><span>Opisz krótko sprawę…</span></div><span class="zmh-sample-button">Wyślij zapytanie →</span></div></div>
<?php }
function zm_home_commerce_visual(): void { ?>
<div class="zmh-visual"><div class="zmh-commerce zmh-glass"><div class="zmh-voucher"><small>NATURA STUDIO</small><strong>Chwila<br>dla Ciebie.</strong><span>VOUCHER PODARUNKOWY</span></div><div class="zmh-commerce-copy"><p class="zmh-caption">PRZYKŁADOWY ZAKUP</p><h3>Pomysł<br>na prezent.</h3><p>Produkt → Koszyk → Płatność</p><small>Demonstracja zakupu vouchera.</small></div></div></div>
<?php }
function zm_home_flow_visual(bool $aftercare = false): void {
    $items = $aftercare ? [['✓','Zakończenie'],['☏','Kontakt po usłudze'],['▦','Kolejny krok']] : [['✉','Nowe zapytanie'],['▤','Wycena'],['✓','Realizacja']]; ?>
<div class="zmh-visual"><div class="zmh-flow zmh-glass"><?php foreach ($items as $i=>[$icon,$label]) : ?><?php if ($i>0) : ?><i aria-hidden="true">→</i><?php endif; ?><div class="zmh-flow-item<?php echo $i===0 ? ' zmh-active' : ''; ?>"><span aria-hidden="true"><?php echo esc_html($icon); ?></span><b><?php echo esc_html($label); ?></b></div><?php endforeach; ?></div><p class="zmh-caption zmh-bottom-caption"><?php echo esc_html($aftercare ? 'Przykład opieki nad klientem po realizacji.' : 'Przykładowy przebieg obsługi w systemie.'); ?></p></div>
<?php }
function zm_home_living_portal(bool $contact = false): void { if ($contact) { ?>
<div class="zmh-water-portal" data-living-portal="contact"><div class="zmh-water-orbit" aria-hidden="true"><div class="zmh-water-drop"><video muted loop playsinline preload="none" data-water-video></video><span></span></div><i></i><i></i></div><p>Dobry pomysł.<br><em>Niech płynie dalej.</em></p><button type="button" data-water-toggle>Zatrzymaj wodę Ⅱ</button></div>
<?php } else { ?>
<div id="opowiesc" class="zmh-assembly" data-living-portal><div class="zmh-assembly-heading"><span>Z CHAOSU DO PORZĄDKU</span><h2>Wszystko zaczyna<br>się <em>łączyć.</em></h2><p>Strona. Zapytanie. Kolejny krok.<br>Przewiń i zobacz, jak tworzą całość.</p></div><div class="zmh-assembly-board" aria-label="Ilustracja połączenia strony, zapytania i obsługi klienta"><div class="zmh-assembly-lines" aria-hidden="true"><svg viewBox="0 0 600 400"><path d="M80 90 C300 90 150 310 350 310 S480 210 550 210"></path></svg></div><div class="zmh-piece zmh-piece-web"><small>01 / TWOJA STRONA</small><strong>Dobra firma.<br>Dobry początek.</strong><div class="zmh-piece-photo"></div><span>Oferta · Kontakt ↗</span></div><div class="zmh-piece-inquiry"><small>02 / ZAPYTANIE</small><b>Nowy kontakt <i>✓</i></b><span>Potrzeba · Termin · Szczegóły</span></div><div class="zmh-piece-order"><small>03 / KOLEJNY KROK</small><b>Wszystko na swoim miejscu.</b><span>Zapytanie <i>→</i> Wycena <i>→</i> Realizacja</span></div><span class="zmh-assembly-note">PRZYKŁADOWY PROCES DLA TWOJEJ FIRMY</span></div></div>
<?php }} ?>
<main class="zm-v5">
<a class="zmh-skip" href="#opowiesc">Przejdź do treści</a>
<div class="zmh-forest" id="start">
  <div class="zmh-opening">
    <div class="zmh-living-forest" aria-hidden="true"><video muted loop playsinline preload="none" data-forest-video></video></div><button class="zmh-film-control" type="button" data-forest-toggle>Ⅱ Zatrzymaj tło</button>
    <?php zm_site_header(false); ?>
    <section class="zmh-hero zmh-wrap" aria-labelledby="hero-title">
      <div class="zmh-hero-copy"><p class="zmh-eyebrow">STRONY WWW I SYSTEMY DLA FIRM</p><h1 id="hero-title">Masz dobrą firmę.<br><em>Pokażmy ją z dobrej strony.</em></h1><p class="zmh-lead">Projektuję strony WWW dla firm usługowych. Pomagam też uporządkować zapytania, sprzedaż i obsługę klientów.</p><p class="zmh-service-line"><a href="<?php echo esc_url(home_url('/oferta#branze')); ?>">Formularze</a> · <a href="<?php echo esc_url(home_url('/oferta#mini-sklep')); ?>">Sklepy i płatności</a> · <a href="<?php echo esc_url(home_url('/maly-crm-dla-firm')); ?>">Systemy CRM</a></p><div class="zmh-actions"><a class="zmh-pill" href="#opowiesc">Zobacz możliwości <span aria-hidden="true">↓</span></a><a class="zmh-quiet" href="tel:+48450458466">Porozmawiajmy ↗</a></div><p class="zmh-trust-note">Od pierwszej rozmowy pracujesz bezpośrednio ze mną.<br> Gotową stronę oglądasz i zatwierdzasz przed publikacją.</p></div>
      <div class="zmh-hero-foot"><span class="zmh-aside-note">TWÓJ POMYSŁ.<br>WSPÓLNY KIERUNEK.</span><p>Dobry grunt<br>dla Twoich<br>pomysłów.</p></div>
    </section>
  </div>
  <?php zm_home_living_portal(false); ?>
  <div class="zmh-cinema zmh-wrap">
    <div class="zmh-cinema-chapters">
      <section class="zmh-story" id="twoja-strona" aria-labelledby="strona-title"><div class="zmh-wrap zmh-split"><div class="zmh-copy"><p class="zmh-chapter">01 / TWOJA STRONA</p><h2 id="strona-title">Strona, na której<br>łatwo Cię zrozumieć.</h2><p>Klient widzi, co oferujesz, dla kogo pracujesz i jak się z Tobą skontaktować. Układam treść, zdjęcia i nawigację tak, żeby tworzyły spójną opowieść o Twojej firmie.</p><p class="zmh-callout">Wybieramy to, czego potrzebujesz.<br>Od samej strony po połączone z nią narzędzia.</p><a class="zmh-text-link" href="<?php echo esc_url(home_url('/oferta')); ?>">Co obejmuje strona WWW ↗</a></div><?php zm_home_website_visual(); ?></div></section>
      <section class="zmh-story" aria-labelledby="formularze-title"><div class="zmh-wrap zmh-split"><div class="zmh-copy"><p class="zmh-chapter">02 / FORMULARZE</p><h2 id="formularze-title">Mniej dopytywania.<br>Więcej konkretów.</h2><p>Usługa, preferowany termin, kilka zdań o potrzebie. Dobrze dobrany formularz pomaga klientowi opisać sprawę, a Tobie przygotować rozmowę lub wycenę.</p><span class="zmh-aside-note">WIĘCEJ MIEJSCA<br>NA DOBRĄ ROZMOWĘ.</span></div><?php zm_home_form_visual(); ?></div></section>
      <section class="zmh-story" aria-labelledby="sprzedaz-title"><div class="zmh-wrap zmh-split"><div class="zmh-copy"><p class="zmh-chapter">03 / SKLEP I PŁATNOŚCI</p><h2 id="sprzedaz-title">Twoja oferta sięga<br>dalej niż wizyta.</h2><p>Kosmetyk polecony po zabiegu. Voucher dla kogoś bliskiego. Produkt, po który klient chce wrócić. Łączę stronę ze sklepem i płatnościami online, żeby można było kupić go także z domu.</p><a class="zmh-text-link" href="<?php echo esc_url(home_url('/oferta#mini-sklep')); ?>">Co obejmuje sklep z płatnościami ↗</a></div><?php zm_home_commerce_visual(); ?></div></section>
      <section class="zmh-story" aria-labelledby="crm-title"><div class="zmh-wrap zmh-split"><div class="zmh-copy"><p class="zmh-chapter">04 / CRM I OBSŁUGA ZLECEŃ</p><h2 id="crm-title">Zapytanie przyszło.<br>Wiadomo, co dalej.</h2><p>Gdy ustalenia mają swoje miejsce, łatwiej zaplanować dzień. CRM to system, w którym łączę kontakty, wyceny, terminy i statusy zleceń. Wiesz, komu odpowiedzieć i co jest już zrobione.</p><a class="zmh-text-link" href="<?php echo esc_url(home_url('/maly-crm-dla-firm')); ?>">Zobacz, jak działa CRM ↗</a></div><?php zm_home_flow_visual(false); ?></div></section>
      <section class="zmh-story zmh-relationships" aria-labelledby="relacje-title"><div class="zmh-wrap zmh-split"><div class="zmh-copy"><p class="zmh-chapter">05 / KONTAKT PO USŁUDZE</p><h2 id="relacje-title">Dobre relacje<br>warto pielęgnować.</h2><p>Po wykonanej usłudze zostaje miejsce na pytanie, czy wszystko w porządku, prośbę o opinię albo przypomnienie o kolejnym terminie. Pomagam zaplanować taki kontakt i połączyć go z obsługą zleceń.</p></div><?php zm_home_flow_visual(true); ?></div></section>
    </div>
    <div class="zmh-motion-intro zmh-wrap"><p>Przewijaj, aby zobaczyć, jak łączą się kolejne etapy.</p><button type="button" data-story-motion-toggle>Ogranicz ruch</button></div>
    <aside class="zmh-cinema-stage" aria-hidden="true"><div class="zmh-cinema-screen"><div class="zmh-cinema-status"><span>STRONA · PROCES · RELACJA</span><span class="cinema-counter">01 / 05</span></div><div class="zmh-cinema-shots" data-cinema-shots></div><div class="zmh-cinema-rail"><span></span></div><div class="zmh-cinema-dots"><i></i><i></i><i></i><i></i><i></i></div></div></aside>
  </div>
</div>
<div class="zmh-lower-forest">
  <section class="zmh-portfolio zmh-wrap" id="projekty" aria-labelledby="projekty-title"><div class="zmh-section-heading"><div><p class="zmh-eyebrow">PROJEKTY DEMONSTRACYJNE</p><h2 id="projekty-title">Zobacz, zanim zdecydujesz.</h2></div><a class="zmh-pill zmh-outline" href="<?php echo esc_url(home_url('/realizacje')); ?>">Obejrzyj projekty ↗</a></div><p class="zmh-intro">Sprawdź, jak strona pomaga wybrać usługę, zaplanować wizytę albo znaleźć mieszkanie. Każdy przykład odpowiada na inną potrzebę.</p><div class="zmh-projects"><a class="zmh-project zmh-glass" href="<?php echo esc_url(home_url('/demo/natura-strona')); ?>"><img src="<?php echo esc_url(zm_theme_asset('assets/images/concept-natura.jpg')); ?>" width="600" height="400" loading="lazy" alt="Wnętrze demonstracyjnego studia wellness"><div><small>DEMONSTRACJA / BEAUTY</small><h3>Natura Studio</h3><p>Wybór zabiegu zaczyna się od jasnego opisu. Strona pokazuje usługi, ceny i drogę do umówienia wizyty.</p><span>Obejrzyj stronę studia ↗</span></div></a><a class="zmh-project zmh-glass zmh-bistro" href="<?php echo esc_url(home_url('/demo/bistro-strona')); ?>"><img src="<?php echo esc_url(zm_theme_asset('assets/images/concept-bistro.jpg')); ?>" width="600" height="400" loading="lazy" alt="Wnętrze demonstracyjnej restauracji"><div><small>DEMONSTRACJA / GASTRONOMIA</small><h3>Bistro Forma</h3><p>Gość chce poczuć klimat miejsca i zaplanować wizytę. Strona łączy menu z informacją o rezerwacji.</p><span>Obejrzyj stronę restauracji ↗</span></div></a></div><div class="zmh-more-projects"><a href="<?php echo esc_url(home_url('/demo/dom-strona')); ?>">Dom Dobry / mieszkania i dostępność ↗</a><a href="<?php echo esc_url(home_url('/demo/routeflow/index.html')); ?>">RouteFlow / strona firmy transportowej ↗</a></div><p class="zmh-caption">Autorskie demonstracje możliwości. Nie są realizacjami dla klientów.</p></section>
  <section class="zmh-process zmh-wrap" id="proces" aria-labelledby="proces-title"><p class="zmh-chapter">WSPÓŁPRACA Z ZIELONĄ MARKĄ</p><h2 id="proces-title">Spokojny proces.<br>Wspólny kierunek.</h2><p>Mam na imię Łukasz. Tworzę strony i proste narzędzia, które ułatwiają kontakt z klientami i codzienną pracę firmy. Zaczynam od rozmowy o tym, czego potrzebujesz, a potem proponuję rozwiązanie i zakres prac. Rozmawiasz bezpośrednio ze mną i wiesz, co przygotowujemy oraz co będziesz zatwierdzać.</p><figure class="zmh-founder-photo"><img src="<?php echo esc_url(zm_theme_asset('assets/images/lukasz-zielona-marka-strona-glowna-20260908.webp')); ?>" width="1000" height="563" loading="lazy" alt="Łukasz podczas konsultacji projektu"><figcaption>Rozmawiasz bezpośrednio ze mną, od pomysłu po gotową stronę.</figcaption></figure><ol class="zmh-care-steps"><li><span>01</span><h3>Ustalamy zakres</h3><p>Wybieramy potrzebne funkcje i uzgadniamy zakres przed rozpoczęciem prac.</p></li><li><span>02</span><h3>Przygotowuję projekt</h3><p>Układam treści, wygląd i narzędzia. Ty oglądasz gotową propozycję.</p></li><li><span>03</span><h3>Ty zatwierdzasz</h3><p>Sprawdzam działanie strony. Publikacja następuje po Twojej akceptacji.</p></li></ol><a class="zmh-text-link" href="<?php echo esc_url(home_url('/jak-pracuje')); ?>">Przeczytaj zasady współpracy ↗</a></section>
  <section class="zmh-story zmh-grow" aria-labelledby="rozwoj-title"><div class="zmh-wrap zmh-split"><div class="zmh-copy"><p class="zmh-chapter">PO PUBLIKACJI / OPIEKA NAD STRONĄ</p><h2 id="rozwoj-title">Rozwój w rytmie<br>Twojej firmy.</h2><p>Nowa usługa, pomysł na sprzedaż, wygodniejszy sposób obsługi. Stronę można rozbudować, gdy pojawi się taka potrzeba. Dalszą opiekę i nowe funkcje ustalamy osobno, w zakresie dopasowanym do Twojej firmy.</p></div><div class="zmh-growth-words"><a href="<?php echo esc_url(home_url('/opieka-nad-strona')); ?>">Opieka ↗</a><a href="<?php echo esc_url(home_url('/usprawnienia-firmy#automatyzacje')); ?>">Usprawnienia ↗</a><a href="<?php echo esc_url(home_url('/opieka-nad-strona#rozwoj')); ?>">Rozwój ↗</a></div></div></section>
  <section class="zmh-contact zmh-wrap" id="kontakt" aria-labelledby="kontakt-title"><?php zm_home_living_portal(true); ?><div><p class="zmh-eyebrow">ZACZNIJMY OD ROZMOWY</p><h2 id="kontakt-title">Zróbmy miejsce<br>na <em>dobrą zmianę.</em></h2><p>Opowiedz, czym zajmuje się Twoja firma i co chcesz ułatwić sobie lub klientom. Wystarczy kilka zdań. Pomogę Ci wybrać kierunek i ustalić, od czego warto zacząć.</p><a class="zmh-pill" href="tel:+48450458466">Porozmawiajmy ↗</a><a class="zmh-phone" href="tel:+48450458466">+48 450 458 466</a><details class="zmh-contact-draft"><summary>Wolisz napisać? Opisz swoją sprawę <span aria-hidden="true">+</span></summary><div class="zmh-form-surface"><h3>Kilka zdań na dobry początek.</h3><p>Opisz swoją firmę i to, co chcesz zmienić. Szczegóły możemy ustalić w rozmowie.</p><?php zm_render_home_contact_form(); ?></div></details></div></section>
  <?php zm_site_footer(false); ?>
</div>
<?php zm_quick_whatsapp(); ?>
</main>
<?php get_footer('bare'); ?>
