<?php
get_header();
$projects=[
['01','Natura Studio','Wellness i uroda','Projekt koncepcyjny / demonstracja','Spokojna strona usługowa z prostą drogą do kontaktu i rezerwacji.','https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/concept-natura.jpg','/demo/natura-strona'],
['02','Bistro Forma','Gastronomia','Projekt koncepcyjny / demonstracja','Menu, klimat miejsca, rezerwacja stolika i codzienna obsługa w jednym kierunku.','https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/concept-bistro.jpg','/demo/bistro-strona'],
['03','Dom Dobry','Nieruchomości','Projekt koncepcyjny / demonstracja','Czytelna prezentacja inwestycji, dostępności i drogi od oglądania do zapytania.','https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/concept-dom.jpg','/demo/dom-strona'],
['04','Auto Naprawa','Warsztat i obsługa klienta','Projekt koncepcyjny / demonstracja','Strona warsztatu, portal klienta, kosztorysy, faktury i widok dla kierownika.','https://lukaszst-cz.github.io/operations-office-portfolio/auto-naprawa-preview/assets/workshop-hero.png','https://lukaszst-cz.github.io/operations-office-portfolio/auto-naprawa-preview/'],
['05','TransportFlow','Transport i logistyka','Projekt koncepcyjny / demonstracja','Demonstracyjny system TMS i CRM: zlecenia, kierowcy, dokumenty oraz wyniki firmy.','https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/og.png','/realizacje/transportflow'],
['06','DetailFlow','Auto detailing','Projekt koncepcyjny / demonstracja','System dla zapytań, stanowisk, kontroli jakości, zdjęć, płatności i powrotów klientów.','https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/og.png','/realizacje/detailflow'],
];
?>
<main>
<section class="page-hero shell"><span class="eyebrow"><i></i>REALIZACJE I DEMONSTRACJE</span><h1>Nie jeden szablon dla wszystkich. <em>Różne cele, różne układy.</em></h1><p>Prezentowane projekty pokazują możliwe kierunki dla konkretnych branż. Są wyraźnie oznaczone jako demonstracje, dopóki nie zastąpią ich realizacje klientów.</p><a class="button" href="#projekty">Zobacz projekty <span>↓</span></a></section>
<section id="projekty" class="section shell"><div class="project-list"><?php foreach($projects as $p): $href=strpos($p[6],'http')===0?$p[6]:home_url($p[6]); ?><article class="project-case"><div class="project-case-image" style="background-image:linear-gradient(115deg,rgba(10,31,22,.84),rgba(10,31,22,.12)),url('<?php echo esc_url($p[5]); ?>')"><span><?php echo esc_html($p[3]); ?></span><b><?php echo esc_html($p[0]); ?></b></div><div><small><?php echo esc_html($p[2]); ?></small><h2><?php echo esc_html($p[1]); ?></h2><p><?php echo esc_html($p[4]); ?></p><div class="project-case-links"><a class="button" href="<?php echo esc_url($href); ?>">Zobacz projekt <span>↗</span></a></div></div></article><?php endforeach; ?></div></section>
<section class="section dark-section"><div class="shell operations-grid"><div><span class="section-no">DEMONSTRACJA: TRANSPORT</span><h2>TransportFlow porządkuje zlecenie od pierwszego zapytania do płatności.</h2><p>Demonstracyjny TMS i CRM dla floty: zlecenia, kierowcy, dokumenty, KPI, terminy płatności oraz widoki dla klienta i kierowcy.</p></div><div><a class="button button-light" href="<?php echo esc_url(home_url('/realizacje/transportflow')); ?>">Poznaj TransportFlow <span>↗</span></a><a href="https://transportflow.zielona-marka.pl" target="_blank" rel="noreferrer">Otwórz demonstrację ↗</a></div></div></section>
<section class="section shell next-project"><span class="section-no">TWOJA FIRMA</span><h2>Masz branżę, której jeszcze nie ma w portfolio?</h2><p>Nie kopiuję układu z innego projektu. Zaczynamy od tego, co klient Twojej firmy musi znaleźć i zrobić.</p><a class="button" href="<?php echo esc_url(home_url('/kontakt')); ?>">Porozmawiajmy o projekcie <span>↗</span></a></section>
</main><?php get_footer(); ?>