<?php
get_header();
$steps=[['01','Brief i cel','Krótka rozmowa, najważniejszy problem i ustalenie zakresu.'],['02','Struktura i treści','Porządkujemy ofertę oraz decydujemy, co klient ma zrobić na stronie.'],['03','Jeden kierunek projektu','Otrzymujesz konkretny układ strony i widok mobilny do akceptacji.'],['04','Wdrożenie','Powstaje działająca strona, formularze, kontakt i uzgodnione funkcje.'],['05','Testy jakości','Sprawdzam telefon, komputer, linki, formularze, szybkość i podstawy SEO.'],['06','Odbiór, 70% i publikacja','Po akceptacji i rozliczeniu pozostałych 70% publikuję stronę na serwerze klienta, przekazuję dostępy, instrukcję i 14 dni wsparcia.']];
$faq=[['Czy musimy spotykać się osobiście?','Nie. Współpraca może odbywać się przez Google Meet, telefon, e-mail i WhatsApp. Działam lokalnie, ale realizuję projekty zdalnie dla firm z całej Polski.'],['Czy mogę samodzielnie edytować treść?','Tak, jeśli projekt tego wymaga. Przed startem wybieramy prosty sposób aktualizacji, np. WordPress, albo ustalamy zakres opieki nad stroną.'],['Ile propozycji projektu otrzymam?','Pracujemy na jednym, dopasowanym kierunku projektu. Dzięki temu zamiast wybierać przypadkowy szablon, poprawiamy rozwiązanie przygotowane dla Twojej firmy.'],['Ile poprawek obejmuje projekt?','W uzgodnionym zakresie są dwie rundy poprawek. Nowe funkcje, kolejne podstrony lub zmiana kierunku po akceptacji są wyceniane osobno przed rozpoczęciem.'],['Czy strona będzie widoczna w Google?','Przygotowuję techniczne podstawy: strukturę, opisy, wersję mobilną, szybkość i możliwość zgłoszenia strony do Google. Nie obiecuję konkretnej pozycji.'],['Co oznacza QA?','QA to końcowa kontrola jakości. Sprawdzam telefon, komputer, formularze, linki, szybkość, podstawową dostępność oraz pełną ścieżkę klienta.'],['Co dzieje się po publikacji?','Przekazuję uzgodnione dostępy, instrukcję i 14 dni podstawowego wsparcia startowego. Dalsza opieka jest opcjonalna.'],['Jak wygląda płatność 30/70?','30% zaliczki po akceptacji zakresu i umowy rezerwuje termin i rozpoczyna pracę. Pozostałe 70% jest płatne po akceptacji gotowej wersji i testach QA, przed publikacją.']];
?>
<main>
<section class="page-hero shell"><span class="eyebrow"><i></i>JAK PRACUJĘ</span><h1>Jasne decyzje od pierwszej rozmowy <em>do działającej strony.</em></h1><p>Nie musisz prowadzić projektu technicznie. Wiesz, czego potrzebuję od Ciebie, co robię na danym etapie i kiedy podejmujemy decyzję.</p><a class="button" href="<?php echo esc_url(home_url('/kontakt')); ?>">Zacznij od briefu <span>↗</span></a></section>
<section class="section shell"><div class="section-head"><div><span class="section-no">PROCES</span><h2>Od pomysłu do publikacji.</h2></div><p>Typowa mała strona firmowa zajmuje zwykle 1–3 tygodnie od otrzymania materiałów. Dokładny termin zależy od zakresu i szybkości decyzji.</p></div><div class="timeline"><?php foreach($steps as $s): ?><article><span><?php echo esc_html($s[0]); ?></span><h3><?php echo esc_html($s[1]); ?></h3><p><?php echo esc_html($s[2]); ?></p></article><?php endforeach; ?></div></section>
<section class="section qa-section"><div class="shell qa-grid"><div><span class="section-no">TESTY JAKOŚCI / QA</span><h2>Strona jest testowana, zanim zacznie pracować na Twoją firmę.</h2><p class="spaced-copy">Na koniec otrzymujesz proste podsumowanie kontroli: co zostało sprawdzone i co jest gotowe do startu.</p><div class="qa-seal" aria-hidden="true"><span>QA</span><b>✓</b></div></div><div><ul class="check-list"><li>telefon, tablet i komputer</li><li>formularze, e-mail, numer telefonu i WhatsApp</li><li>linki, przekierowania i podstawowe błędy</li><li>szybkość oraz stabilność</li><li>przygotowanie do Google i mapa strony</li><li>podstawowa dostępność oraz czytelność</li></ul></div></div></section>
<section class="section rules-section"><div class="shell rules-grid"><article><span>30%</span><h3>Zaliczka na start</h3><p>Po akceptacji zakresu i umowy rezerwuję termin oraz rozpoczynam pracę.</p></article><article><span>70%</span><h3>Przed publikacją</h3><p>Po odbiorze gotowej wersji i testach QA, przed publikacją na serwerze klienta.</p></article><article><span>02</span><h3>Dwie rundy poprawek</h3><p>Uwagi zbieramy i wprowadzamy w jasno określonym zakresie.</p></article><article><span>14</span><h3>Dni wsparcia startowego</h3><p>Po publikacji pomagam spokojnie przejść przez pierwsze dni działania strony.</p></article></div></section>
<section class="section shell faq-page"><div class="section-head"><div><span class="section-no">FAQ</span><h2>Najważniejsze odpowiedzi przed startem.</h2></div><p>Krótko, konkretnie i bez technicznego żargonu.</p></div><div class="faq-list"><?php foreach($faq as $i=>$q): ?><details<?php echo $i===0?' open':''; ?>><summary><span><?php echo esc_html(sprintf('%02d',$i+1)); ?></span><?php echo esc_html($q[0]); ?><i>+</i></summary><p><?php echo esc_html($q[1]); ?></p></details><?php endforeach; ?></div></section>
</main><?php get_footer(); ?>