<!doctype html>
<html <?php language_attributes(); ?>>
<head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class('status-entry'); ?>><?php wp_body_open(); ?>
<main class="status-entry">
<nav class="nav shell"><a class="brand" href="<?php echo esc_url(home_url('/')); ?>"><span class="brand-signature"><img class="brand-apple" src="https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/logo-zielona-marka-transparent-v1.png" alt=""><span class="brand-wordmark"><b>ZIELONA</b><b>MARKA</b><small>STRONY WWW I SYSTEMY DLA FIRM</small></span></span></a><a href="<?php echo esc_url(home_url('/')); ?>">Strona główna</a></nav>
<section class="status-intro"><div><span class="section-no">STREFA KLIENTA</span><h1>Wiesz, co dzieje się z Twoim projektem.</h1><p>Po rejestracji zlecenia otrzymujesz indywidualny kod. Dzięki niemu samodzielnie sprawdzisz postęp, najbliższy krok, termin i dokumenty.</p></div><form data-status-form><label>Kod projektu<input name="code" placeholder="ZM-XXXX-XXXX-XXXX" autocomplete="off" required></label><button class="button">Otwórz status <span>↗</span></button><small>Kod dostałeś/-aś w wiadomości po rejestracji projektu.</small></form></section>
<section class="status-benefits shell"><?php foreach([['01','Aktualny etap','Widzisz, na jakim etapie jest praca i ile zostało do kolejnego kroku.'],['02','Jedno miejsce','Zakres, termin, informacja od wykonawcy i umowa są zawsze pod tym samym adresem.'],['03','Bezpieczny dostęp','Kod otwiera tylko Twój projekt. Nie jest publiczną listą realizacji.']] as $row): ?><article><b><?php echo esc_html($row[0]); ?></b><h2><?php echo esc_html($row[1]); ?></h2><p><?php echo esc_html($row[2]); ?></p></article><?php endforeach; ?></section>
<section class="status-note shell"><div><span class="section-no">PRZEJRZYSTA WSPÓŁPRACA</span><h2>Nie musisz pytać, czy coś już jest gotowe.</h2></div><p>Gdy potrzebne będą materiały, akceptacja lub podpisana umowa, zobaczysz konkretną informację w statusie. Przed publikacją projekt przechodzi kontrolę jakości (QA): telefon, komputer, formularze, linki i podstawowe SEO.</p></section>
<p class="status-security shell">Kod daje dostęp tylko do jednego projektu. Nie udostępniaj go osobom postronnym. W razie problemu napisz na <a href="mailto:kontakt@zielona-marka.pl">kontakt@zielona-marka.pl</a>.</p>
</main><?php wp_footer(); ?></body></html>