<?php
get_header();
$symptoms=['strona źle wygląda na telefonie','oferta jest nieczytelna albo zbyt ogólna','telefon i formularz nie są pod ręką','klienci nie wiedzą, co zrobić dalej','treści są nieaktualne','strona działa wolno','dane w Google i na stronie są niespójne','nie wiadomo, skąd przychodzą zapytania'];
$fixes=['odświeżenie układu, zdjęć i hierarchii treści','pierwszy ekran z jasną ofertą i kontaktem','klikalny telefon, WhatsApp i formularz','wersja mobilna zaprojektowana świadomie','sprawdzenie linków, formularzy oraz szybkości','podstawy technicznego SEO i uporządkowane dane firmy'];
?>
<main>
<section class="page-hero shell"><span class="eyebrow"><i></i>MODERNIZACJA STRONY</span><h1>Twoja firma się rozwinęła. <em>Strona może ją dogonić.</em></h1><p>Nie każda stara strona wymaga budowania od zera. Najpierw sprawdzam, co blokuje kontakt i czy opłaca się poprawiać obecny serwis.</p><a class="button" href="#miniaudyt">Poproś o miniocenę <span>↓</span></a></section>
<section class="section shell"><div class="section-head"><div><span class="section-no">ROZPOZNAJ PROBLEM</span><h2>Jeśli znasz choć dwa z tych objawów, warto przyjrzeć się stronie.</h2></div><p>Modernizacja nie polega na zmianie kolorów. Jej celem jest uproszczenie drogi klienta od wejścia na stronę do telefonu, wiadomości albo zakupu.</p></div><div class="symptom-grid"><?php foreach($symptoms as $i=>$s): ?><article><b><?php echo esc_html(sprintf('%02d',$i+1)); ?></b><span><?php echo esc_html($s); ?></span></article><?php endforeach; ?></div></section>
<section class="section dark-section"><div class="shell rebuild-grid"><div><span class="section-no">CO ZMIENIAMY</span><h2>Najpierw klient musi zrozumieć ofertę. <em>Dopiero potem zachwycać się wyglądem.</em></h2></div><ul class="check-list light-list"><?php foreach($fixes as $fix): ?><li><?php echo esc_html($fix); ?></li><?php endforeach; ?></ul></div></section>
<section class="section shell decision-grid"><article><span>WARIANT 01</span><h2>Poprawiamy obecną stronę</h2><p>Wybieramy go, gdy techniczny fundament jest dobry, a problemem są przede wszystkim treść, wygląd, kontakt i wersja mobilna.</p><ul><li>krótszy czas realizacji</li><li>mniej kosztów</li><li>zachowanie obecnego adresu i treści</li></ul></article><article><span>WARIANT 02</span><h2>Budujemy od nowa</h2><p>To lepsza opcja, gdy strona jest bardzo wolna, trudna w edycji, niebezpieczna lub jej układ nie pozwala już spokojnie rosnąć.</p><ul><li>nowa struktura i kierunek wizualny</li><li>czyste przygotowanie do Google</li><li>prostsza rozbudowa w przyszłości</li></ul></article></section>
<section class="section contact-section" id="miniaudyt"><div class="shell contact-grid"><div><span class="section-no">BEZPŁATNA MINI OCENA</span><h2>Wyślij adres strony. Wskażę, od czego warto zacząć.</h2><p>Otrzymasz krótką, konkretną odpowiedź dotyczącą telefonu, oferty, kontaktu i najważniejszego następnego kroku. Bez deklarowania budżetu.</p><a class="text-link" href="<?php echo esc_url(home_url('/oferta')); ?>">Zobacz pakiety modernizacji <span>↗</span></a></div><div><?php zm_render_contact_form(true); ?></div></div></section>
</main><?php get_footer(); ?>