<?php get_header(); ?>
<main>
<section class="industry-sales-hero industry-sales-auto"><div class="shell"><span class="eyebrow"><i></i>STRONY DLA WARSZTATÓW I DETAILINGU</span><h1>Klient opisuje auto i usterkę. Ty dostajesz konkretne zgłoszenie.</h1><p>Strona warsztatu może zebrać markę i model pojazdu, objawy, zdjęcia oraz oczekiwany termin jeszcze przed pierwszym telefonem.</p><div class="hero-actions"><a class="button" href="#demo">Wypróbuj formularz <span>↓</span></a><a class="text-link" href="<?php echo esc_url(home_url('/kontakt')); ?>">Zapytaj o wdrożenie <span>↗</span></a></div></div></section>

<section class="section shell industry-outcomes"><div><span class="section-no">CO ZYSKUJE FIRMA</span><h2>Nie tylko nowy wygląd. Lepszy pierwszy kontakt.</h2><p>Warsztaty mechaniczne, detailing, wulkanizacja, klimatyzacja, blacharstwo, lakiernictwo, serwisy motocykli i pomoc drogowa.</p></div><ul><li><b>01</b>mniej niepełnych pytań o cenę</li><li><b>02</b>zdjęcia i dane auta przy zgłoszeniu</li><li><b>03</b>czytelna oferta usług i obszar działania</li><li><b>04</b>telefon, formularz i Google w jednej ścieżce</li></ul></section>

<section class="section shell industry-practice"><div><span class="section-no">STRONA WARSZTATU W PRAKTYCE</span><h2>Klient wie, gdzie trafić. Ty wiesz, czego dotyczy sprawa.</h2></div><div><p>Dobra strona warsztatu nie zastępuje rozmowy z mechanikiem. Ułatwia jej początek: pokazuje usługi, obszar działania, najważniejsze opinie oraz wygodny kontakt. Formularz może zebrać markę auta, opis problemu, zdjęcia i preferowany termin.</p><p>Jeżeli zapytań jest więcej, można później dodać proste zaplecze: listę spraw, status „do wyceny”, „umówione” lub „zakończone” i krótkie notatki. To mały CRM, czyli prosty porządek w codziennej pracy, a nie kosztowny system dla dużej korporacji.</p></div></section>

<section class="section leadflow-section" id="demo"><div class="shell leadflow-grid"><div><span class="section-no">ZOBACZ ŚCIEŻKĘ KLIENTA</span><h2>Krótki formularz zamienia ogólne pytanie w uporządkowane zgłoszenie.</h2><p>To bezpieczna demonstracja, wpisane dane pozostają w przeglądarce i nie są wysyłane. W prawdziwej wersji zgłoszenie trafia do e-maila lub panelu firmy.</p></div><div class="leadflow-demo"><span>INTERAKTYWNE DEMO · NIC NIE WYSYŁAMY</span><h3>Zgłoszenie do warsztatu</h3><p>Tak klient może przekazać dane potrzebne do odpowiedzi, wyceny lub rezerwacji.</p><form onsubmit="return false;"><label>Czego dotyczy zgłoszenie?<select><option>Wybierz usługę</option><option>Diagnostyka / naprawa</option><option>Serwis okresowy</option><option>Detailing</option><option>Opony / klimatyzacja</option></select></label><label>Marka, model i objawy<textarea rows="4" placeholder="Np. Skoda Octavia, kontrolka silnika, nierówna praca…"></textarea></label><label>Preferowany termin<input type="text" placeholder="Np. wtorek po 15:00"></label><label>Zdjęcia (w prawdziwym wdrożeniu)<input type="file" disabled></label><label>Telefon lub e-mail<input type="text" placeholder="Jak firma ma odpowiedzieć?"></label><button class="button" type="button" data-demo-submit>Zasymuluj zgłoszenie <span>↗</span></button></form><p class="demo-result" data-demo-result hidden>✓ Przykładowe zgłoszenie zostało uporządkowane lokalnie. Nic nie wysłano.</p></div></div></section>

<section class="section shell industry-flow-section" data-workshop-flow><div class="section-head"><div><span class="section-no">INTERAKTYWNA ŚCIEŻKA OBSŁUGI</span><h2>Po zgłoszeniu firma nadal wie, co zrobić.</h2></div><p>Kliknij etap, aby zobaczyć przykład informacji i następnego kroku. To demonstracja sposobu działania, nie działający system klienta.</p></div><div class="industry-flow-tabs"><button class="active" type="button" data-flow-step="0"><b>01</b>Nowe zgłoszenie</button><button type="button" data-flow-step="1"><b>02</b>Wstępna ocena</button><button type="button" data-flow-step="2"><b>03</b>Termin lub wycena</button><button type="button" data-flow-step="3"><b>04</b>Status sprawy</button></div><article class="industry-flow-panel"><span>AKTUALNY ETAP</span><h3 data-flow-title>Nowe zgłoszenie</h3><p data-flow-copy>Klient podaje auto, problem, zdjęcia i dogodny termin.</p><small>Wynik dla firmy</small><b data-flow-result>Właściwa informacja trafia do właściwej osoby.</b></article></section>

<section class="section shell industry-package"><div><span class="section-no">REKOMENDOWANY PAKIET</span><h2>ZM LeadFlow</h2><p>Strona do 6 podstron, formularz kwalifikujący, widoczność lokalna w Google, analityka, kontrola jakości (QA) i 14 dni wsparcia.</p></div><div><strong>od 4 490 zł netto</strong><span>10–14 dni roboczych</span><small>30% na start · 70% po odbiorze i kontroli jakości (QA), przed publikacją</small><a class="button" href="<?php echo esc_url(home_url('/kontakt')); ?>">Porozmawiajmy o Twojej firmie <b>↗</b></a></div></section>
</main><?php get_footer(); ?>