<?php
get_header();
$packages=[
['PAKIET 01','ZM Start','od 2 490 zł netto','Jedna konkretna strona dla lokalnej firmy, która ma prowadzić z Google do telefonu lub zapytania.',['One Page do ok. 7 sekcji, oferta i kontakt','telefon, WhatsApp, mapa oraz formularz','wersja mobilna i podstawy lokalnego SEO','podłączenie domeny lub hostingu klienta','testy jakości, publikacja i 14 dni wsparcia'],'zwykle 7 dni roboczych'],
['PAKIET 02','ZM LeadFlow','od 4 490 zł netto','Strona i formularz kwalifikujący, dzięki którym firma otrzymuje kompletne zgłoszenia zamiast ogólnych pytań.',['do 6 podstron i indywidualny układ','formularz z opisem, terminem i możliwością dodania zdjęć','lokalne SEO, analityka i przygotowanie Profilu Firmy Google','dwie rundy poprawek, raport QA i 14 dni wsparcia'],'zwykle 10–14 dni roboczych'],
['PAKIET 03','ZM Flow AI','od 6 900 zł netto','Strona, formularz i asystent połączone z prostym obiegiem zapytań w firmie.',['strona oraz formularz kwalifikujący','asystent FAQ lub AI oparty na zatwierdzonej bazie odpowiedzi','przekazanie zgłoszeń do właściciela lub zespołu','testy scenariuszy, analityka, publikacja i 14 dni wsparcia'],'zwykle 14–21 dni roboczych']
];
$extras=[['Wizytówka Google i widoczność w okolicy','od 390 zł','Porządek w danych firmy, usługach, opisie i kontakcie między Mapami Google a stroną.'],['Teksty na stronę','od 350 zł','Pomoc w zamianie wiedzy o firmie w prostą ofertę, którą klient rozumie.'],['Opieka nad stroną','249–490 zł / mies.','Kontrola działania, formularzy, aktualizacji i drobne zmiany po publikacji.'],['Asystent FAQ i zbieranie kontaktów','od 2 500 zł + od 199 zł / mies.','Odpowiedzi z zatwierdzonej bazy wiedzy, kwalifikacja potrzeby oraz przekazanie kontaktu człowiekowi.'],['Przypomnienia SMS','od 690 zł + koszt SMS','Konfiguracja przypomnień o terminie, szablonu wiadomości i zgody klienta.'],['Backup na dysku klienta','od 990 zł + 49 zł / mies.','Automatyczna kopia danych na dysku Google klienta lub w innym uzgodnionym magazynie.'],['Mały CRM z wersją na telefon','od 4 900 zł','Klienci, zapytania, statusy, terminy, eksport danych i mobilny panel.']];
?>
<main>
<section class="page-hero shell"><span class="eyebrow"><i></i>OFERTA I CENY</span><h1>Wybierz efekt dla firmy, <em>nie technologię.</em></h1><p>Każda kwota jest punktem startu dla jasno określonego zakresu. Przed pracą dostajesz prostą propozycję: co wykonuję, ile to zajmie i ile kosztuje.</p><a class="button" href="<?php echo esc_url(home_url('/kontakt')); ?>">Poproś o dokładną wycenę <span>↗</span></a></section>
<section class="section shell"><div class="core-package-grid offer-page-packages"><?php foreach($packages as $i=>$p): ?><article<?php echo $i===1?' class="featured"':''; ?>><span><?php echo esc_html($p[0]); ?></span><div class="package-number">0<?php echo esc_html((string)($i+1)); ?></div><h2><?php echo esc_html($p[1]); ?></h2><b><?php echo esc_html($p[2]); ?></b><p><?php echo esc_html($p[3]); ?></p><ul><?php foreach($p[4] as $x): ?><li><?php echo esc_html($x); ?></li><?php endforeach; ?></ul><small><?php echo esc_html($p[5]); ?></small><a href="<?php echo esc_url(home_url('/kontakt')); ?>">Zapytaj o pakiet <i>↗</i></a></article><?php endforeach; ?></div></section>
<section id="branze" class="section mini-shop-section"><div class="shell mini-shop-grid"><div><span class="section-no">TRZY SPRAWDZONE ŚCIEŻKI</span><h2>Inne dane zbiera warsztat, inne wykonawca, a inne salon beauty.</h2><p class="spaced-copy">W każdym wdrożeniu formularz i asystent wynikają z prawdziwego sposobu obsługi klienta.</p><div class="mini-shop-visual" aria-hidden="true"><i></i><i></i><i></i></div></div><div><h3>Wybierz przykład</h3><ul class="check-list"><li><a href="<?php echo esc_url(home_url('/strony-dla-warsztatow')); ?>">warsztat i detailing ↗</a></li><li><a href="<?php echo esc_url(home_url('/strony-dla-firm-uslugowych')); ?>">remonty, instalacje i serwis ↗</a></li><li><a href="<?php echo esc_url(home_url('/strony-dla-beauty')); ?>">beauty i usługi na termin ↗</a></li><li><a href="<?php echo esc_url(home_url('/asystent-zapytan')); ?>">asystent i kwalifikacja zapytania ↗</a></li></ul></div></div></section>
<section class="section crm-offer"><div class="shell crm-offer-grid"><div><span class="section-no">MAŁY CRM — WAŻNY FILAR OFERTY</span><h2>Strona zdobywa kontakt. Mały CRM pilnuje, żeby firma go nie zgubiła.</h2><p>Porządkuje klientów, zapytania, wyceny, statusy zleceń, terminy i następne działania.</p></div><div><b>od 4 900 zł netto</b><span>zwykle 3–4 tygodnie</span><a class="button" href="<?php echo esc_url(home_url('/maly-crm-dla-firm')); ?>">Zobacz Mały CRM <i>↗</i></a></div></div></section>
<section id="mini-sklep" class="section mini-shop-section beauty-shop-section"><div class="shell mini-shop-grid"><div><span class="section-no">MINI SKLEP / 3–10 PRODUKTÓW</span><h2>Usługa może prowadzić do rezerwacji w Booksy, a produkt do bezpiecznego zakupu.</h2><p class="spaced-copy">Dla salonu beauty, fryzjera, gabinetu, twórcy lub lokalnej marki.</p><b class="shop-price">3 499–5 499 zł</b><p class="muted">Zwykle 3–5 tygodni, zależnie od materiałów i operatora płatności.</p></div><div><h3>Co obejmuje</h3><ul class="check-list"><li>około 3–10 produktów i warianty</li><li>koszyk oraz jeden operator płatności</li><li>odbiór osobisty lub proste formy dostawy</li><li>vouchery albo zestawy</li><li>wersja mobilna i test całego zakupu</li></ul></div></div></section>
<section class="section shell"><div class="section-head"><div><span class="section-no">DODATKI, KTÓRE MAJĄ SENS</span><h2>Dobierane do realnej potrzeby.</h2></div><p>Nie dokładam funkcji tylko dlatego, że można. Każdy element ma pomóc zdobyć kontakt, uprościć obsługę albo utrzymać stronę w dobrej kondycji.</p></div><div class="extra-grid"><?php foreach($extras as $x): ?><article><span><?php echo esc_html($x[1]); ?></span><h3><?php echo esc_html($x[0]); ?></h3><p><?php echo esc_html($x[2]); ?></p><a href="<?php echo esc_url(strpos($x[0],'CRM')!==false?home_url('/maly-crm-dla-firm'):home_url('/kontakt')); ?>">Zapytaj o zakres ↗</a></article><?php endforeach; ?></div></section>
<section id="koszty-zewnetrzne" class="section external-costs"><div class="shell"><div class="section-head"><div><span class="section-no">JASNE KOSZTY ZEWNĘTRZNE</span><h2>Wiesz, kto za co płaci — przed uruchomieniem.</h2></div><p>W cenie wdrożenia jest uzgodniona praca projektowa i techniczna. Usługi dostawców zewnętrznych klient opłaca bezpośrednio.</p></div><div class="external-cost-grid"><article><span>01</span><h3>Płatności w sklepie</h3><p>Integrujemy sklep z uzgodnionym operatorem płatności. Konto u operatora należy do klienta.</p></article><article><span>02</span><h3>SMS i rezerwacje</h3><p>Przypomnienia SMS są opcjonalne, a koszt wiadomości rozlicza wybrany dostawca.</p></article><article><span>03</span><h3>AI i asystent</h3><p>Asystent FAQ może działać bez AI. Wariant AI wymaga uzgodnionego konta API i limitu.</p></article><article><span>04</span><h3>Backup i utrzymanie</h3><p>Eksport danych jest częścią CRM, a automatyczny backup można podłączyć opcjonalnie.</p></article></div></div></section>
<section class="section estimate-section"><div class="shell estimate-grid"><div><span class="section-no">SZYBKA WYCENA</span><h2>Sprawdź orientacyjny punkt startu.</h2><p class="spaced-copy">Wynik pomaga rozpocząć rozmowę. Dokładna oferta zależy od funkcji, materiałów, integracji i terminu.</p></div><div class="estimate-calculator" data-estimator><span>ORIENTACYJNY BUDŻET</span><h3>Sprawdź punkt startu projektu.</h3><label>Rodzaj projektu<select data-estimator-type><option value="2490">ZM Start — strona One Page</option><option value="4490" selected>ZM LeadFlow — strona i formularz</option><option value="6900">ZM Flow AI — strona, formularz i asystent</option><option value="2500">ZM Bot FAQ — asystent do istniejącej strony</option><option value="4900">Prosty panel zleceń (mały CRM)</option></select></label><label><input type="checkbox" data-estimator-copy> Pomoc w przygotowaniu tekstów</label><label><input type="checkbox" data-estimator-google> Uporządkowanie wizytówki Google</label><div><small>ORIENTACYJNIE OD</small><b data-estimator-value>4 490 zł</b><p>Dokładną cenę ustalam po krótkim briefie i zakresie prac.</p></div></div></div></section>
<section class="section shell price-rules"><div><span class="section-no">JASNE ZASADY 30/70</span><h2>Najpierw odbierasz gotową stronę, potem publikujemy ją u Ciebie.</h2></div><ol><li><b>30% zaliczki</b> po akceptacji zakresu i umowy rezerwuje termin.</li><li><b>Wersja robocza</b> jest przedstawiana do akceptacji i dwóch rund poprawek.</li><li><b>70% po odbiorze i QA</b> jest płatne przed publikacją.</li><li><b>Publikacja i przekazanie</b> następują po pełnym rozliczeniu.</li></ol></section>
</main><?php get_footer(); ?>