<?php
get_header();
$packages=[
['KOMPLETNA STRONA STARTOWA','ZM Start','od 1 449 zł netto','Kompletna, jedna przewijana strona dla małej firmy: oferta, kontakt i prosta droga od Google do telefonu lub zapytania.',['indywidualny układ do ok. 6–7 sekcji','telefon, WhatsApp, mapa oraz formularz','wersja mobilna, podstawy Google i podłączenie domeny','dwie rundy poprawek oraz testy jakości','publikacja, instrukcja i 14 dni wsparcia'],'Mała, podstawowa strona: od 72 godzin do 14 dni od otrzymania kompletu materiałów i ustalenia zakresu'],
['PAKIET 02','ZM LeadFlow','od 4 490 zł netto','Strona i formularz kwalifikujący, dzięki którym firma otrzymuje kompletne zgłoszenia zamiast ogólnych pytań.',['do 6 podstron i indywidualny układ','formularz z opisem, terminem i możliwością dodania zdjęć','lokalne SEO, analityka i przygotowanie Profilu Firmy Google','dwie rundy poprawek, raport kontroli jakości (QA) i 14 dni wsparcia'],'zwykle 10–14 dni roboczych'],
['PAKIET 03','ZM Flow','od 6 900 zł netto','Strona, formularz i automatyczny asystent połączone z prostym obiegiem zapytań w firmie.',['strona oraz formularz kwalifikujący','automatyczny asystent oparty na zatwierdzonej bazie odpowiedzi','przekazanie zgłoszeń do właściciela lub zespołu','testy scenariuszy, analityka i ścieżka dalszej rozbudowy'],'zwykle 14–21 dni roboczych']
];
$extras=[
['Wizytówka Google i widoczność w okolicy','od 390 zł','Porządek w danych firmy, usługach, opisie i kontakcie między Mapami Google a stroną. To podstawy lokalnego SEO, czyli widoczności w wyszukiwarce.'],
['Teksty na stronę','od 350 zł','Pomoc w zamianie wiedzy o firmie w prostą ofertę, którą klient rozumie.'],
['Opieka nad stroną','249–490 zł / mies.','Kontrola działania, formularzy, aktualizacji i drobne zmiany po publikacji.'],
['Asystent zapytań FAQ i zbieranie kontaktów','od 2 500 zł + od 199 zł / mies.','Odpowiedzi z zatwierdzonej bazy wiedzy, kwalifikacja potrzeby oraz przekazanie kontaktu człowiekowi.'],
['Przypomnienia SMS','od 690 zł + koszt SMS','Konfiguracja przypomnień o terminie, szablonu wiadomości i zgody klienta. Koszt SMS rozlicza wybrana bramka.'],
['Backup na dysku klienta','od 990 zł + 49 zł / mies.','Automatyczna kopia danych na dysku Google klienta lub w innym uzgodnionym magazynie, wraz z kontrolą działania.'],
['Mały CRM z wersją na telefon','od 4 900 zł','Klienci, zapytania, statusy, terminy, eksport danych i panel, który można dodać do ekranu telefonu jak aplikację.']
];
?>
<main>
<section class="page-hero shell"><span class="eyebrow"><i></i>OD DOBREJ FIRMY DO DOBRZE PROWADZONEGO KLIENTA</span><h1>Wybierz efekt dla firmy, <em>nie technologię.</em></h1><p>Strona ma pokazać wartość Twojej pracy, formularz ma zebrać konkrety, a CRM ma dopilnować następnego kroku. Wszystkie ceny usług Zielonej Marki są cenami netto. Każda kwota jest punktem startu dla jasno określonego zakresu.</p><a class="button" href="<?php echo esc_url(home_url('/kontakt')); ?>">Poproś o dokładną wycenę <span>↗</span></a></section>

<section class="section shell"><div class="core-package-grid offer-page-packages"><?php foreach($packages as $i=>$p): ?><article<?php echo $i===1?' class="featured"':''; ?>><span><?php echo esc_html($p[0]); ?></span><div class="package-number">0<?php echo esc_html((string)($i+1)); ?></div><h2><?php echo esc_html($p[1]); ?></h2><b><?php echo esc_html($p[2]); ?></b><p><?php echo esc_html($p[3]); ?></p><ul><?php foreach($p[4] as $x): ?><li><?php echo esc_html($x); ?></li><?php endforeach; ?></ul><small><?php echo esc_html($p[5]); ?></small><a href="<?php echo esc_url(home_url('/kontakt')); ?>">Zapytaj o pakiet <i>↗</i></a></article><?php endforeach; ?></div></section>

<section class="section start-package-detail"><div class="shell start-package-grid"><div><span class="section-no">ZM START / OD 1 449 ZŁ NETTO</span><h2>Pełna strona dla firmy, która chce być dobrze znaleziona i łatwa do kontaktu.</h2><p>To nie jest wersja „okrojona”. Zakres jest celowo skupiony na jednej, dobrze zaprojektowanej stronie, zamiast na wielu podstronach i funkcjach, których mała firma jeszcze nie potrzebuje.</p><a class="button" href="<?php echo esc_url(home_url('/kontakt')); ?>">Zapytaj o ZM Start <span>↗</span></a></div><div><h3>Co dokładnie otrzymujesz</h3><ul class="check-list"><li>indywidualny układ do około 6–7 sekcji</li><li>oferta, najważniejsze korzyści, proces i kontakt</li><li>menu, klikalny telefon, e-mail, WhatsApp oraz mapa lub obszar działania</li><li>formularz kontaktowy zabezpieczony przed prostym spamem</li><li>wersja na telefon, tablet i komputer</li><li>podstawy widoczności w Google: tytuł, opis, logiczne nagłówki, mapa strony i dane firmy</li><li>grafika do udostępniania, favicon oraz podłączenie domeny i HTTPS</li><li>dwie rundy poprawek, kontrola jakości (QA), publikacja, instrukcja i 14 dni wsparcia</li></ul><p class="legal-note">Cena startowa dotyczy strony z materiałami dostarczonymi przez klienta. Dodatkowe podstrony, sklep, rezerwacje, panel klienta, mały CRM, pełne teksty od zera oraz płatne usługi zewnętrzne ustalamy przed rozpoczęciem.</p></div></div></section>

<section id="branze" class="section mini-shop-section"><div class="shell mini-shop-grid"><div><span class="section-no">TRZY SPRAWDZONE ŚCIEŻKI</span><h2>Inne dane zbiera warsztat, inne wykonawca, a inne salon beauty.</h2><p class="spaced-copy">W każdym wdrożeniu formularz i asystent zapytań wynikają z prawdziwego sposobu obsługi klienta.</p><div class="mini-shop-visual" aria-hidden="true"><i></i><i></i><i></i></div></div><div><h3>Wybierz przykład</h3><ul class="check-list"><li><a href="<?php echo esc_url(home_url('/strony-dla-warsztatow')); ?>">warsztat i detailing ↗</a></li><li><a href="<?php echo esc_url(home_url('/strony-dla-firm-uslugowych')); ?>">remonty, instalacje i serwis ↗</a></li><li><a href="<?php echo esc_url(home_url('/strony-dla-beauty')); ?>">beauty i usługi na termin ↗</a></li><li><a href="<?php echo esc_url(home_url('/asystent-zapytan')); ?>">asystent i kwalifikacja zapytania ↗</a></li></ul><p class="legal-note">Pokrewne branże dobieramy według procesu: wycena zdalna, przyjęcie zlecenia albo rezerwacja wizyty.</p></div></div></section>

<section class="section crm-offer"><div class="shell crm-offer-grid"><div><span class="section-no">MAŁY CRM, WAŻNY FILAR OFERTY</span><h2>Strona zdobywa kontakt. Mały CRM pilnuje, żeby firma go nie zgubiła.</h2><p>Porządkuje klientów, zapytania, wyceny, statusy zleceń, terminy i następne działania. Może działać samodzielnie albo razem ze stroną i formularzami.</p></div><div><b>od 4 900 zł netto</b><span>zwykle 3–4 tygodnie</span><a class="button" href="<?php echo esc_url(home_url('/maly-crm-dla-firm')); ?>">Zobacz Mały CRM <i>↗</i></a></div></div></section>

<section id="mini-sklep" class="section mini-shop-section beauty-shop-section"><div class="shell mini-shop-grid"><div><span class="section-no">MINI SKLEP / 3–10 PRODUKTÓW</span><h2>Usługa może prowadzić do rezerwacji w Booksy, a produkt do bezpiecznego zakupu.</h2><p class="spaced-copy">Dla salonu beauty, fryzjera, gabinetu, twórcy lub lokalnej marki. Strona może sprzedawać kosmetyki, vouchery, zestawy pielęgnacyjne i inne wybrane produkty bez budowania wielkiego sklepu.</p><b class="shop-price">3 499–5 499 zł netto</b><p class="muted">Zwykle 3–5 tygodni, zależnie od materiałów i operatora płatności.</p><div class="mini-shop-visual" aria-hidden="true"><i></i><i></i><i></i></div></div><div><h3>Co obejmuje</h3><ul class="check-list"><li>około 3–10 produktów i warianty</li><li>koszyk oraz jeden operator płatności</li><li>odbiór osobisty lub proste formy dostawy</li><li>vouchery albo zestawy, jeśli zakres to przewiduje</li><li>osobna ścieżka „Umów usługę w Booksy”</li><li>wersja mobilna i test całego zakupu</li></ul><p class="legal-note">Sprzedawcą, właścicielem regulaminu, płatności i danych klientów pozostaje firma klienta. Nietypowe magazyny, subskrypcje i rozbudowane integracje wyceniamy osobno.</p></div></div></section>

<section class="section shell"><div class="section-head"><div><span class="section-no">DODATKI, KTÓRE MAJĄ SENS</span><h2>Dobierane do realnej potrzeby.</h2></div><p>Nie dokładam funkcji tylko dlatego, że „można”. Każdy element ma pomóc zdobyć kontakt, uprościć obsługę albo utrzymać stronę w dobrej kondycji.</p></div><div class="extra-grid"><?php foreach($extras as $x): ?><article><span><?php echo esc_html($x[1]); ?></span><h3><?php echo esc_html($x[0]); ?></h3><p><?php echo esc_html($x[2]); ?></p><a href="<?php echo esc_url(strpos($x[0],'CRM')!==false?home_url('/maly-crm-dla-firm'):home_url('/kontakt')); ?>"><?php echo strpos($x[0],'CRM')!==false?'Zobacz rozwiązanie':'Zapytaj o zakres'; ?> ↗</a></article><?php endforeach; ?></div></section>

<section id="koszty-zewnetrzne" class="section external-costs"><div class="shell"><div class="section-head"><div><span class="section-no">JASNE KOSZTY ZEWNĘTRZNE</span><h2>Wiesz, kto za co płaci, przed uruchomieniem.</h2></div><p>W cenie wdrożenia jest uzgodniona praca projektowa i techniczna. Usługi dostawców zewnętrznych klient opłaca bezpośrednio, po akceptacji aktualnych stawek.</p></div><div class="external-cost-grid">
<article><span>01</span><h3>Płatności w sklepie</h3><p>Integrujemy sklepy z Przelewy24, Tpay i Stripe. Umowę oraz konto u operatora zawiera klient; prowizja trafia bezpośrednio do operatora.</p><small>Przykładowo: Przelewy24 1,29% + 0,30 zł; Tpay Starter 1,59% + 0,39 zł; Stripe BLIK 1,6% + 1 zł za transakcję.</small></article>
<article><span>02</span><h3>SMS i rezerwacje</h3><p>Przypomnienia SMS są opcjonalne. Konfigurujemy je, a koszt wiadomości rozlicza bramka SMS wybrana przez klienta.</p><small>Przykład: SMSAPI ok. 0,14–0,17 zł netto za SMS przy małej skali. Booksy lub inny system rezerwacji ma własny plan klienta.</small></article>
<article><span>03</span><h3>Automatyzacja zapytań</h3><p>Asystent może działać według prostego scenariusza. Wariant rozszerzony wymaga własnego konta technicznego, miesięcznego limitu i zatwierdzonej bazy odpowiedzi.</p><small>Firma może korzystać z własnego konta technicznego albo wybrać obsługę od 199 zł netto miesięcznie. Prywatna subskrypcja rozmów nie jest wymagana.</small></article>
<article><span>04</span><h3>Backup i utrzymanie</h3><p>Eksport danych jest częścią CRM. Automatyczny backup na dysku Google klienta lub innym magazynie podłączamy opcjonalnie.</p><small>Backup od 990 zł netto za konfigurację + 49 zł netto miesięcznie za kontrolę. Domena, hosting i dodatkowa przestrzeń są uzgadniane osobno.</small></article>
</div><p class="legal-note external-note">Podane prowizje operatorów i koszty usług zewnętrznych są przykładami; mogą się zmienić. Przed uruchomieniem potwierdzamy aktualną stawkę i właściciela każdego konta.</p></div></section>

<section class="section estimate-section"><div class="shell estimate-grid"><div><span class="section-no">SZYBKA WYCENA</span><h2>Sprawdź orientacyjny punkt startu.</h2><p class="spaced-copy">Wynik pomaga rozpocząć rozmowę. Dokładna oferta zależy od funkcji, materiałów, integracji i terminu.</p><p class="spaced-copy spaced-copy-follow">Nie musisz wpisywać budżetu w formularzu. Najpierw ustalimy, co ma zmienić się w firmie.</p></div><div class="estimate-calculator" data-estimator><span>ORIENTACYJNY BUDŻET</span><h3>Sprawdź punkt startu projektu.</h3><label>Rodzaj projektu<select data-estimator-type><option value="1449">ZM Start — strona One Page</option><option value="4490" selected>ZM LeadFlow — strona i formularz</option><option value="6900">ZM Flow — strona, formularz i asystent</option><option value="2500">Asystent FAQ do istniejącej strony</option><option value="4900">Prosty panel zleceń (mały CRM)</option></select></label><label><input type="checkbox" data-estimator-copy> Pomoc w przygotowaniu tekstów</label><label><input type="checkbox" data-estimator-google> Uporządkowanie wizytówki Google</label><div><small>ORIENTACYJNIE OD</small><b data-estimator-value>4 490 zł netto</b><p>Dokładną cenę ustalam po krótkim briefie i zakresie prac.</p></div></div></div></section>

<section class="section shell price-rules"><div><span class="section-no">JASNE ZASADY 30/70</span><h2>Najpierw odbierasz gotową stronę, potem publikujemy ją u Ciebie.</h2></div><ol><li><b>30% zaliczki</b> po akceptacji zakresu i umowy rezerwuje termin i rozpoczyna pracę.</li><li><b>Wersja robocza</b> jest przedstawiana pod bezpiecznym adresem do akceptacji i dwóch rund poprawek.</li><li><b>70% po odbiorze i kontroli jakości (QA)</b> jest płatne przed publikacją na domenie lub serwerze klienta.</li><li><b>Publikacja i przekazanie</b> następują po pełnym rozliczeniu; koszty zewnętrzne są zatwierdzane osobno.</li></ol></section>
</main>
<?php get_footer(); ?>
