<?php get_header(); $modules=[['01','Zlecenia i realizacja','Trasa, pojazd, kierowca, etap, ETA, koszt oraz marża w jednym rejestrze.'],['02','Flota i kierowcy','50 zestawów, dostępność, serwis, spalanie, dokumenty, czas pracy i indywidualne karty 58 kierowców.'],['03','Dokumenty','Obieg od zapytania do faktury, CMR, POD, zdjęcia po dostawie, terminy, wersje i blokady procesu.'],['04','CRM klientów','Relacje, oferty, limity kredytowe, historia współpracy i osobny widok dla klienta.'],['05','Finanse i płatności','Marża, należności, warunki handlowe, terminy zapłaty oraz sprawy wymagające kontaktu.'],['06','KPI zarządcze','Przychód, wykorzystanie floty, puste kilometry, ryzyko dokumentowe i bieżące decyzje.']]; ?>
<main>
<section class="page-hero shell"><span class="eyebrow"><i></i>REALIZACJA DLA TRANSPORTU</span><h1>Transport nie musi być prowadzony między telefonem, arkuszem i dokumentami.</h1><p>TransportFlow to demonstracyjny TMS i CRM dla firmy zarządzającej flotą około 50 zestawów ciężarowych. Łączy codzienną dyspozycję, kierowców, klientów, dokumenty i pieniądze w jednym spójnym obiegu.</p><div class="hero-actions"><a class="button" href="https://transportflow.zielona-marka.pl" target="_blank" rel="noreferrer">Zobacz demonstrację <span>↗</span></a><a class="text-link" href="#jak-powstal">Jak powstał system <span>↓</span></a></div><p class="legal-note">Wszystkie dane w demonstracji są syntetyczne. System pokazuje sposób organizacji pracy, nie dane prawdziwej firmy.</p></section>

<section class="section dark-section"><div class="shell operations-grid"><div><span class="section-no">PUNKT WYJŚCIA</span><h2>Najwięcej czasu nie znika na trasie. Znika pomiędzy ludźmi i rozproszonymi informacjami.</h2></div><div><p>Jedna osoba ma zlecenie, druga dokument, kierowca wysyła zdjęcie, klient pyta o termin, a księgowość czeka na komplet do rozliczenia. Gdy te elementy nie są połączone, firma pracuje wolniej i dowiaduje się o problemie zbyt późno.</p><p>Dlatego celem nie był kolejny ekran z tabelą. Celem było narzędzie, które skraca obieg informacji i pozwala szybciej podejmować decyzje.</p></div></div></section>

<section class="section shell"><div class="section-head"><div><span class="section-no">CO PORZĄDKUJE SYSTEM</span><h2>Jeden proces, sześć najważniejszych obszarów.</h2></div><p>Każdy moduł ma odpowiadać na konkretne pytanie operacyjne, a nie tylko zbierać dane dla samego zbierania.</p></div><div class="crm-module-grid"><?php foreach($modules as $m):?><article><span><?php echo esc_html($m[0]);?></span><h3><?php echo esc_html($m[1]);?></h3><p><?php echo esc_html($m[2]);?></p></article><?php endforeach;?></div></section>

<section class="section operations-section"><div class="shell operations-grid"><div><span class="section-no">DOKUMENTY BEZ SZUKANIA</span><h2>Po dostawie kierowca potwierdza wykonanie cyfrowo albo dołącza zdjęcie czy PDF.</h2></div><div><p>Dokument jest przypisany do firmy, pojazdu, kierowcy albo konkretnego zlecenia. Ma status, termin, wersję i regułę blokady. Jeżeli brakuje dokumentu potrzebnego do załadunku, system pokazuje to przed rozpoczęciem pracy.</p><p>To skraca drogę od samochodu do biura i przyspiesza przekazanie kompletu do rozliczenia.</p></div></div></section>

<section class="section shell"><div class="section-head"><div><span class="section-no">KPI I PIENIĄDZE</span><h2>Właściciel widzi nie tylko wynik. Widzi, gdzie trzeba zareagować.</h2></div><p>Pulpit KPI prowadzi od liczby do źródłowego rejestru. Nie kończy się na kolorowym wykresie.</p></div><div class="problem-grid"><article><span>01</span><h3>Rentowność</h3><p>Przychód, koszt i marża aktywnych zleceń pozwalają szybko ocenić wynik operacyjny.</p></article><article><span>02</span><h3>Flota</h3><p>Wykorzystanie zestawów, serwis i puste kilometry pokazują, gdzie ucieka czas albo pieniądze.</p></article><article><span>03</span><h3>Należności</h3><p>Warunki płatności, pozycje po terminie i wykorzystanie limitu klienta tworzą kolejkę do działania.</p></article><article><span>04</span><h3>Ryzyko</h3><p>Blokady dokumentowe i sprawy pilne pomagają reagować zanim wpłyną na trasę lub rozliczenie.</p></article></div></section>

<section class="section crm-mobile"><div class="shell crm-mobile-grid"><div><span class="section-no">MOBILNIE I WEDŁUG ROLI</span><h2>Kierowca, klient i biuro widzą <em>to, co jest im potrzebne.</em></h2><p>Kierowca ma własne zadania oraz dokumenty na telefonie. Klient widzi wyłącznie własne przewozy, etap realizacji i dokumenty swojej firmy. Zespół biurowy pracuje na operacjach, finansach, flocie albo relacjach.</p><small>System jest przygotowany jako PWA, więc można dodać go do ekranu telefonu lub tabletu jak aplikację.</small></div><div class="crm-phone" aria-label="Przykładowy widok mobilny TransportFlow"><header><b>TRANSPORTFLOW / DZISIAJ</b><span>9:41</span></header><strong>Moja trasa</strong><article><i></i>Załadunek potwierdzony</article><article><i></i>Dokument dostawy do przekazania</article><article><i></i>Następny etap: rozliczenie</article><footer>Własne zlecenia i dokumenty pod ręką</footer></div></div></section>

<section class="section shell" id="jak-powstal"><div class="section-head"><div><span class="section-no">JAK POWSTAŁ</span><h2>Zacząłem od procesu firmy, a dopiero potem od technologii.</h2></div><p>To podejście pozwala tworzyć system, który wspiera rzeczywistą pracę zamiast wymuszać pracę pod gotowy szablon.</p></div><div class="industry-outcomes"><div><p>Najpierw rozpisaliśmy pełny cykl zlecenia: zapytanie, oferta, planowanie, załadunek, transport, dostawa, dokumenty, faktura i płatność. Następnie określiłem właściciela każdego etapu, wymagane dane, wyjątki oraz miejsca, w których proces powinien zatrzymać się automatycznie.</p><p>Dopiero na tej podstawie powstały moduły, widoki ról i pulpit zarządczy. Dzięki temu kierowca ma prosty ekran, dyspozytor ma operacje, a właściciel ma wynik i listę decyzji.</p></div><ul><li><b>01</b><span>Model procesu i odpowiedzialności</span></li><li><b>02</b><span>Model danych: zlecenia, pojazdy, kierowcy, klienci i dokumenty</span></li><li><b>03</b><span>Interfejs dla biura, kierowcy i klienta</span></li><li><b>04</b><span>KPI, dokumenty, terminy i kontrola jakości</span></li></ul></div></section>

<section class="section dark-section"><div class="shell operations-grid"><div><span class="section-no">ZAPLECZE ROZWIĄZANIA</span><h2>Technologia ma być niewidoczna wtedy, gdy wszystko działa.</h2></div><div><p>TransportFlow został zaprojektowany tak, aby działał na komputerze i telefonie, rozdzielał widoki według roli oraz pozwalał rozwijać kolejne moduły bez przebudowy całego procesu.</p><p>W realnym wdrożeniu zakres integracji dobieramy do systemów używanych przez firmę: księgowości, telematyki, paliwa, dokumentów i komunikacji z klientem. Najpierw ustalamy proces, dopiero potem narzędzia.</p><a class="text-link" href="https://transportflow.zielona-marka.pl" target="_blank" rel="noreferrer">Sprawdź działającą demonstrację <span>↗</span></a></div></div></section>

<section class="section shell next-project"><span class="section-no">CO TO DAJE FIRMIE</span><h2>Mniej ręcznego przekazywania informacji. Krótsze obiegi. Więcej kontroli.</h2><p>TransportFlow ma dać właścicielowi spokój i kontrolę, dyspozytorowi porządek, kierowcy prostotę, księgowości komplet dokumentów, a klientowi jasny status współpracy.</p><div class="hero-actions"><a class="button" href="https://transportflow.zielona-marka.pl" target="_blank" rel="noreferrer">Otwórz demonstrację <span>↗</span></a><a class="text-link" href="<?php echo esc_url(home_url('/kontakt')); ?>">Porozmawiajmy o wdrożeniu <span>↗</span></a></div></section>
</main><?php get_footer(); ?>