<!doctype html>
<html lang="en">
<head>
<meta charset="<?php bloginfo('charset'); ?>">
<meta name="viewport" content="width=device-width,initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class('english-site live-home'); ?>>
<?php wp_body_open(); ?>
<a class="skip-link screen-reader-text" href="#main-content">Skip to content</a>

<header class="site-header">
<nav class="nav shell" aria-label="Main navigation">
<a class="brand" href="<?php echo esc_url(home_url('/en')); ?>" aria-label="Zielona Marka, English home"><span class="brand-signature"><img class="brand-apple" src="https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/logo-zielona-marka-transparent-v1.png" alt=""><span class="brand-wordmark"><b>ZIELONA</b><b>MARKA</b><small>STRONY WWW I SYSTEMY DLA FIRM</small></span></span></a>
<div class="nav-links">
<details class="nav-offer"><summary>Services <span aria-hidden="true">⌄</span></summary><div class="nav-offer-panel"><a href="#website">Websites</a><a href="#website">Website redesign</a><a href="#crm">CRM and client service</a><a href="#care">Process automation</a><a href="#website">Service businesses</a><a href="#shop">Beauty</a><a href="#forms">Car workshops</a><a href="#contact">Enquiry assistant</a><a href="#contact">Business chatbot</a><a href="#contact">Local websites</a></div></details>
<a href="#projects">Projects</a><a href="#working-together">Working together</a><a href="#contact">Contact</a><a href="<?php echo esc_url(home_url('/status')); ?>">Client area (PL)</a>
</div>
<div class="language-switch"><a href="<?php echo esc_url(home_url('/')); ?>" lang="pl">🇵🇱 <span>PL</span></a><a class="active" href="<?php echo esc_url(home_url('/en')); ?>" lang="en">🇬🇧 <span>EN</span></a></div>
<details class="mobile-menu"><summary>Menu <span>+</span></summary><div><a href="#website">Services</a><a href="#projects">Projects</a><a href="#working-together">Working together</a><a href="#contact">Contact</a><a href="<?php echo esc_url(home_url('/status')); ?>">Client area (PL)</a><a href="<?php echo esc_url(home_url('/')); ?>">Polski</a><a href="tel:+48450458466">+48 450 458 466</a></div></details>
</nav>
</header>

<main id="main-content" class="live-home" lang="en">
<section class="live-hero section-dark">
<div class="live-shell live-hero-grid"><div class="live-hero-copy"><p class="live-kicker">WEBSITES AND SYSTEMS FOR BUSINESSES</p><h1>You have a good business.<br><em>Let’s show it at its best.</em></h1><p class="live-lead">I design websites for service businesses. I also help organise enquiries, sales and customer service.</p><p class="live-links"><a href="#forms">Forms</a> · <a href="#shop">Shops and payments</a> · <a href="#crm">CRM systems</a></p><div class="live-actions"><a class="live-button live-button-light" href="#website">Explore the possibilities ↓</a><a class="live-text-link" href="#contact">Let’s talk ↗</a></div><div class="live-proof"><span>You work directly with me from the first conversation.</span><span>You review and approve your website before it goes live.</span></div></div><div class="live-hero-art" aria-hidden="true"><span>YOUR IDEA.</span><b>A SHARED DIRECTION.</b><strong>Room for<br>your ideas<br>to grow.</strong></div></div>
</section>

<section class="live-story">
<article class="live-story-row section-sage" id="website"><div class="live-shell live-two-col"><div><p class="live-step">01 / YOUR WEBSITE</p><h2>A website that makes your business clear.</h2><p>Customers can see what you offer, who you help and how to contact you. I bring content, photographs and navigation together into a clear story about your business.</p><a class="live-text-link dark" href="<?php echo esc_url(home_url('/oferta')); ?>">Website scope and prices (PL) ↗</a></div><div class="live-demo-card beauty-demo"><small>Wellness website concept · demonstration</small><div class="demo-nav"><b>✳ Natura Studio</b><span>About</span><span>Services</span><span>Contact</span></div><p>TIME FOR YOURSELF</p><h3>Calmer.<br>Closer to you.</h3><p>Care. Relaxation. Natural beauty.</p><a href="<?php echo esc_url(home_url('/demo/natura-strona')); ?>">Explore treatments ↗</a></div></div></article>

<article class="live-story-row section-cream" id="forms"><div class="live-shell live-two-col reverse"><div><p class="live-step">02 / ENQUIRY FORMS</p><h2>Less back and forth. More useful details.</h2><p>A service, a preferred date and a few words about what is needed. A well-designed form helps a customer explain their request and helps you prepare a conversation or quote.</p></div><div class="live-demo-card form-demo"><small>ILLUSTRATIVE SERVICE FORM</small><h3>Ask about a service</h3><label>Service<select><option>Choose a service</option></select></label><label>Date<input type="text" placeholder="Preferred date"></label><label>Details<textarea rows="4" placeholder="Tell us what you need…"></textarea></label><button type="button">Send enquiry →</button></div></div></article>

<article class="live-story-row section-pink" id="shop"><div class="live-shell live-two-col"><div><p class="live-step">03 / SHOP AND PAYMENTS</p><h2>Your offer reaches beyond a visit.</h2><p>A product recommended after a treatment. A gift voucher. Something a customer wants to buy again. I can connect your website to a shop and online payments so customers can also buy from home.</p><a class="live-text-link dark" href="<?php echo esc_url(home_url('/oferta#mini-sklep')); ?>">Shop and payment options (PL) ↗</a></div><div class="live-demo-card voucher-demo"><small>NATURA STUDIO</small><p>A moment<br>for you.</p><b>GIFT VOUCHER</b><h3>A thoughtful gift.</h3><p>Product → Basket → Payment</p><small>Voucher purchase demonstration.</small></div></div></article>

<article class="live-story-row section-darkgreen" id="crm"><div class="live-shell live-two-col reverse"><div><p class="live-step">04 / CRM AND ORDERS</p><h2>An enquiry arrives. The next step is clear.</h2><p>When agreements have a place, planning your day gets easier. A CRM brings contacts, quotes, dates and order statuses together. You can see who needs a reply and what has already been completed.</p><a class="live-text-link" href="<?php echo esc_url(home_url('/maly-crm-dla-firm')); ?>">Explore the CRM example (PL) ↗</a></div><div class="live-demo-card crm-demo"><div><b>✉ New enquiry</b><span>→</span><b>▤ Quote</b><span>→</span><b>✓ Delivery</b></div><small>Illustrative workflow.</small></div></div></article>

<article class="live-story-row section-sage"><div class="live-shell live-two-col"><div><p class="live-step">05 / AFTER THE SERVICE</p><h2>Good relationships deserve care.</h2><p>After a service, you may want to check that everything is fine, ask for a review or remind a customer about their next appointment. I help plan that contact and connect it to your order workflow.</p></div><div class="live-demo-card aftercare-demo"><div><b>✓ Completed</b><span>→</span><b>☏ Follow-up</b><span>→</span><b>▦ Next step</b></div><small>Illustrative workflow.</small></div></div></article>
</section>

<section class="live-projects section-light" id="projects"><div class="live-shell"><div class="live-section-head"><div><p class="live-kicker dark">DEMONSTRATION PROJECTS</p><h2>Explore before you decide.</h2></div><a class="live-text-link dark" href="<?php echo esc_url(home_url('/realizacje')); ?>">All projects (PL) ↗</a></div><p class="live-lead dark">See how a website helps someone choose a service, plan a visit or find a home. Each example responds to a different need.</p><div class="live-project-grid"><a href="<?php echo esc_url(home_url('/demo/natura-strona')); ?>"><small>DEMONSTRATION / WELLNESS AND BEAUTY</small><h3>Natura Studio</h3><p>Treatments, prices and a clear path to booking.</p><b>Explore the demo (PL) ↗</b></a><a href="<?php echo esc_url(home_url('/demo/bistro-strona')); ?>"><small>DEMONSTRATION / HOSPITALITY</small><h3>Bistro Forma</h3><p>A restaurant’s atmosphere, menu and reservation information.</p><b>Explore the demo (PL) ↗</b></a><a href="<?php echo esc_url(home_url('/demo/dom-strona')); ?>"><small>DEMONSTRATION / PROPERTY</small><h3>Dom Dobry</h3><p>Homes and availability in a clear enquiry journey.</p><b>Explore the demo (PL) ↗</b></a><a href="<?php echo esc_url(home_url('/realizacje/transportflow')); ?>"><small>DEMONSTRATION / TRANSPORT</small><h3>TransportFlow</h3><p>An operations dashboard and order workflow.</p><b>Explore the demo (PL) ↗</b></a></div><p class="live-disclaimer">Independent demonstrations of possible solutions. These are not client commissions.</p></div></section>

<section class="live-about section-cream" id="working-together"><div class="live-shell live-two-col"><div><p class="live-kicker dark">WORKING WITH ZIELONA MARKA</p><h2>A calm process.<br>A shared direction.</h2><p>My name is Łukasz. We start with a conversation about your business and what you want to make easier. I propose a solution and scope, so you know what we are preparing and what you will approve.</p><p>You work directly with me, from the idea to your finished website.</p></div><ol class="live-steps-list"><li><span>01</span><div><h3>Agree the scope</h3><p>We choose the features you need and agree the scope before work starts.</p></div></li><li><span>02</span><div><h3>Prepare the project</h3><p>I bring together content, design and tools. You review the complete proposal.</p></div></li><li><span>03</span><div><h3>Approve the result</h3><p>I check how the website works. It goes live after your approval.</p></div></li></ol></div></section>

<section class="live-care section-dark" id="care"><div class="live-shell live-two-col"><div><p class="live-kicker">AFTER LAUNCH / WEBSITE CARE</p><h2>Grow at your business’s pace.</h2></div><div><p>A new service, a sales idea or an easier way to help customers. Your website can grow when the need arises. Ongoing care and new features are agreed separately, to suit your business.</p><div class="live-chip-row"><a href="<?php echo esc_url(home_url('/oferta')); ?>">Care ↗</a><a href="<?php echo esc_url(home_url('/usprawnienia-firmy')); ?>">Improvements ↗</a><a href="<?php echo esc_url(home_url('/usprawnienia-firmy')); ?>">Growth ↗</a></div></div></div></section>

<section class="live-contact section-light" id="contact"><div class="live-shell"><div class="live-contact-head"><div><p class="live-kicker dark">LET’S START WITH A CONVERSATION</p><h2>Make room<br>for a good change.</h2><p>Tell me what your company does and what you would like to make easier for yourself or your customers. A few sentences are enough to start. I will help you choose a direction.</p><p><a class="live-button" href="mailto:kontakt@zielona-marka.pl?subject=Website%20enquiry%20from%20zielona-marka.pl">Write about your project ↗</a></p><p><strong>+48 450 458 466</strong></p></div></div></div></section>
</main>

<footer class="site-footer" lang="en"><div class="shell footer-live-grid"><div class="footer-brand-block"><a class="brand" href="<?php echo esc_url(home_url('/en')); ?>"><span class="brand-signature"><img class="brand-apple" src="https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/logo-zielona-marka-transparent-v1.png" alt=""><span class="brand-wordmark"><b>ZIELONA</b><b>MARKA</b><small>STRONY WWW I SYSTEMY DLA FIRM</small></span></span></a><p>Websites and systems for businesses.</p><p>Warsaw, Targówek and nearby. Remote work across Poland.</p></div><div class="footer-column"><h2>Explore</h2><a href="#website">Services</a><a href="#projects">Projects</a><a href="#working-together">Working together</a><a href="<?php echo esc_url(home_url('/status')); ?>">Client area (PL)</a></div><div class="footer-column"><h2>Contact</h2><a href="tel:+48450458466">+48 450 458 466</a><a href="mailto:kontakt@zielona-marka.pl">kontakt@zielona-marka.pl</a><a href="https://www.facebook.com/StudioGraficzneZielonaMarka" target="_blank" rel="noreferrer">Facebook ↗</a><a href="https://www.instagram.com/zielona.marka.pl/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://github.com/lukaszst-cz" target="_blank" rel="noreferrer">GitHub ↗</a></div></div><div class="shell footer-bottom"><small>© <?php echo esc_html(wp_date('Y')); ?> Zielona Marka</small><a href="<?php echo esc_url(home_url('/polityka-prywatnosci')); ?>">Privacy policy (PL)</a><a href="<?php echo esc_url(home_url('/')); ?>">Polski</a></div></footer>

<?php wp_footer(); ?>
</body>
</html>