<?php /* Production mirror: /demo/bistro-strona */ ?>
<main class="bistro-site">
<nav class="bistro-nav"><a class="bistro-wordmark" href="#start"><span>B</span>BISTRO FORMA</a><div><a href="#menu">Menu</a><a href="#historia">O nas</a><a href="#kontakt">Kontakt</a><a href="<?php echo esc_url(home_url('/#realizacje')); ?>">Portfolio</a><a href="<?php echo esc_url(home_url('/')); ?>">Zielona Marka</a></div><a class="bistro-book" href="#rezerwacja">Rezerwuj online</a></nav>
<header id="start" class="bistro-hero"><div class="bistro-hero-copy"><span>WARSZAWA · KUCHNIA SEZONOWA</span><h1>Prosto.<br><em>Świeżo.</em><br>Razem.</h1><p>Codzienna kuchnia oparta na sezonie, dobrym produkcie i swobodnej atmosferze.</p><div><a href="#menu">Zobacz menu ↓</a><a href="#rezerwacja">Zarezerwuj online ↗</a></div></div><figure><img src="https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/concept-bistro.jpg" alt="Stół i potrawy w Bistro Forma"><figcaption><b>FORMA / 01</b><span>Lunch · kolacja · spotkania</span></figcaption></figure><div class="bistro-stamp" aria-hidden="true">LOCAL<br>SEASONAL<br>HONEST</div></header>
<section class="bistro-info"><div><small>DZISIAJ</small><b>12:00–22:00</b></div><div><small>ADRES</small><b>Warszawa · lokal pokazowy</b></div><div><small>REZERWACJE</small><b>+48 450 458 466</b></div><a href="#kontakt">Jak dojechać ↗</a></section>
<section id="menu" class="bistro-menu"><header><span>01 / KARTA</span><h2>Krótka karta.<br>Dużo <em>sezonu.</em></h2><p>Menu demonstracyjne zmienia się razem z dostępnością produktów. Zapytaj obsługę o alergeny i wersje roślinne.</p></header><div class="bistro-menu-list">
<?php foreach ([['01','Na początek','Pieczony kalafior','labneh · pistacje · mięta','29'],['02','Z ognia','Kurczak kukurydziany','młode ziemniaki · sos estragonowy','52'],['03','Roślinnie','Kaszotto z boczniakiem','szparagi · dojrzewający ser','44'],['04','Na słodko','Sernik palony','rabarbar · wanilia · migdał','25']] as $row): ?>
<article><b><?php echo esc_html($row[0]); ?></b><div><small><?php echo esc_html($row[1]); ?></small><h3><?php echo esc_html($row[2]); ?></h3><p><?php echo esc_html($row[3]); ?></p></div><strong><?php echo esc_html($row[4]); ?> zł</strong></article>
<?php endforeach; ?>
</div><footer><span>Pełne menu można aktualizować samodzielnie w panelu.</span><a href="<?php echo esc_url(home_url('/demo/bistro')); ?>">Zobacz zaplecze restauracji ↗</a></footer></section>
<section id="historia" class="bistro-story"><div class="bistro-story-art"><span>FORMA</span><i></i><i></i><i></i></div><div><span>02 / O NAS</span><h2>Miejsce na zwykły dzień i ważny wieczór.</h2><p>Bistro Forma to koncepcyjna marka restauracyjna pokazująca, jak lokal może połączyć charakter, aktualne menu, informacje praktyczne i prostą rezerwację w jednym mobilnym serwisie.</p><ul><li>sezonowa, czytelna karta</li><li>rezerwacja bez szukania numeru</li><li>wydarzenia i aktualności</li></ul></div></section>
<section class="bistro-evening"><div><span>PIĄTKI / 19:00</span><h2>Stół degustacyjny</h2><p>Pięć dań, jeden wspólny stół i produkty wybrane tego samego tygodnia.</p></div><a href="#rezerwacja">Sprawdź termin <b>↗</b></a></section>
<section id="rezerwacja" class="bistro-reservation"><div><span>03 / REZERWACJA</span><h2>Zostaw miejsce<br>na dobry wieczór.</h2></div><div><p>W gotowym wdrożeniu ten przycisk prowadzi do formularza rezerwacji, kalendarza dostępności albo systemu typu Booksy czy Reservio. Klient wybiera termin i liczbę osób online, bez telefonowania.</p><a href="<?php echo esc_url(home_url('/#kontakt')); ?>">Zapytaj o wdrożenie rezerwacji online ↗</a><small>To demonstracja portfolio. Dla prawdziwego lokalu podpinamy jego formularz, kalendarz lub system rezerwacji.</small></div></section>
<footer id="kontakt" class="bistro-footer"><div class="bistro-wordmark"><span>B</span>BISTRO FORMA</div><div><small>GODZINY</small><p>wt–czw 12:00–22:00<br>pt–sob 12:00–23:00<br>nd 12:00–20:00</p></div><div><small>KONTAKT Z REALIZATOREM</small><p><a href="<?php echo esc_url(home_url('/#kontakt')); ?>">Zielona Marka<br>strony i systemy dla firm ↗</a></p></div><div><small>PROJEKT DEMONSTRACYJNY</small><p>Projekt i realizacja:<br><a href="<?php echo esc_url(home_url('/#realizacje')); ?>">Zielona Marka ↗</a></p></div></footer>
</main>
<?php wp_footer(); ?>