<?php
get_header();
$situations=[['Zapytania giną','Formularz może utworzyć wpis w uporządkowanej bazie, wysłać potwierdzenie i przypomnieć o odpowiedzi.'],['Zespół pyta o status','Prosty widok zlecenia pokazuje etap, termin, osobę odpowiedzialną i następny krok.'],['Wyniki są w kilku arkuszach','Najważniejsze liczby mogą trafić na jeden czytelny ekran, bez ręcznego przepisywania.']];
$items=[['Automatyzacje','Powtarzalne czynności wykonywane przez system: powiadomienia, potwierdzenia, statusy, przypomnienia.'],['Baza klientów','Kontakty, zapytania, oferta i kolejny krok w jednym miejscu zamiast w rozmowach i notatkach.'],['Panel klienta','Prywatny status zlecenia, dokumenty i terminy dostępne dla klienta bez kolejnego telefonu.'],['Najważniejsze liczby','Sprzedaż, terminy, zlecenia i obciążenie zespołu widoczne na jednym ekranie.'],['Excel i Google Sheets','Dobry pierwszy etap, gdy firma nie potrzebuje jeszcze rozbudowanego systemu.'],['Łączenie narzędzi','Strona, poczta, kalendarz i używane programy mogą przekazywać sobie informacje automatycznie.']];
?>
<main>
<section class="page-hero shell"><span class="eyebrow"><i></i>PROSTE PANELE I USPRAWNIENIA FIRMY</span><h1>Najpierw strona. Potem <em>mniej ręcznej pracy.</em></h1><p>Mała firma nie potrzebuje dużego systemu na zapas. Wystarczy wybrać jeden proces, który dziś zabiera czas lub powoduje błędy.</p><a class="button" href="<?php echo esc_url(home_url('/kontakt')); ?>">Opowiedz o procesie <span>↗</span></a></section>
<section class="section process-video-section" id="film"><div class="shell process-video-grid"><div><span class="section-no">ZOBACZ, JAK TO DZIAŁA</span><h2>W 20 sekund: od chaosu w wiadomościach do uporządkowanej obsługi.</h2><p>Strona może zbierać zapytania, a prosty panel pomaga pilnować wycen, etapów pracy i kontaktu z klientem. Nie zaczynamy od wielkiego programu, tylko od tego, co faktycznie ułatwi codzienną pracę.</p><a class="text-link" href="<?php echo esc_url(home_url('/kontakt')); ?>">Porozmawiajmy o Twoim procesie <span>↗</span></a></div><div class="process-video-frame"><video controls preload="metadata" poster="https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/social-post-start-zielona-marka-v1.png"><source src="https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/zielona-marka-jak-dziala.mp4" type="video/mp4"></video><small>Film 20 s · strona, panel klientów i zleceń oraz proste automatyzacje</small></div></div></section>
<section class="section shell" id="crm"><div class="section-head"><div><span class="section-no">ZACZYNAMY OD KONKRETU</span><h2>Prosty panel zleceń zamiast chaosu w wiadomościach.</h2></div><p>To może być mały CRM, czyli prosty system dopasowany do Twojej firmy. Zamiast kupować duży program, zaczynamy od klientów, zleceń, statusów i kolejnego kroku.</p></div><div class="situation-grid"><?php foreach($situations as $i=>$x): ?><article><b>0<?php echo esc_html((string)($i+1)); ?></b><h3><?php echo esc_html($x[0]); ?></h3><p><?php echo esc_html($x[1]); ?></p></article><?php endforeach; ?></div></section>
<section class="section dark-section"><div class="shell process-strip"><span>Zapytanie</span><i>→</i><span>Wycena</span><i>→</i><span>Realizacja</span><i>→</i><span>Dokumenty</span><i>→</i><span>Wyniki</span></div></section>
<section class="section shell" id="automatyzacje"><div class="section-head"><div><span class="section-no">AUTOMATYZACJE, PANELE I INTEGRACJE</span><h2>Dobierane wtedy, gdy są potrzebne.</h2></div><p>Możesz zacząć od jednego przepływu. Jeśli działa, spokojnie rozbudujemy go w kolejnym etapie.</p></div><div class="tool-grid"><?php foreach($items as $i=>$x): ?><article><span><?php echo esc_html(sprintf('%02d',$i+1)); ?></span><h3><?php echo esc_html($x[0]); ?></h3><p><?php echo esc_html($x[1]); ?></p></article><?php endforeach; ?></div></section>
<section class="section transport-demo"><div class="shell transport-demo-grid"><div><span class="section-no">DEMONSTRACJA TRANSPORTU</span><h2>Zobacz, jak wygląda obieg zlecenia od zapytania do faktury.</h2><p class="spaced-copy">Przykład TransportFlow pokazuje osobne widoki dla dyspozytora, kierowcy, księgowości oraz klienta.</p></div><div><a class="button" href="<?php echo esc_url(home_url('/realizacje/transportflow')); ?>">Poznaj rozwiązanie <span>↗</span></a><a href="https://transportflow.zielona-marka.pl" target="_blank" rel="noreferrer">Otwórz demonstrację ↗</a></div></div></section>
</main><?php get_footer(); ?>