<?php
get_header();
$modules=[['01','Zapytania','Wszystkie formularze i kontakty w jednej kolejce, z informacją skąd przyszły.'],['02','Następny krok','Przy każdym kliencie wiadomo, kto i kiedy ma oddzwonić, wysłać wycenę albo się przypomnieć.'],['03','Status zlecenia','Nowe, wycena, zaakceptowane, realizacja, odbiór i rozliczenie — etapy dopasowane do firmy.'],['04','Terminy','Daty wizyt, realizacji i ponownych kontaktów bez pilnowania wszystkiego w pamięci.'],['05','Historia klienta','Kontakt, ustalenia, wartość oferty i wykonane prace dostępne w jednym miejscu.'],['06','Proste wyniki','Liczba zapytań, wysłanych ofert, przyjętych zleceń i ich wartość bez skomplikowanych raportów.']];
?>
<main>
<section class="page-hero shell crm-page-hero"><span class="eyebrow"><i></i>MAŁY CRM DLA FIRMY USŁUGOWEJ</span><h1>Każdy klient ma status. <em>Każde zapytanie ma następny krok.</em></h1><p>Mały CRM porządkuje klientów, wyceny, zlecenia i terminy bez wdrażania rozbudowanego systemu korporacyjnego.</p><div class="hero-actions"><a class="button" href="#moduly">Zobacz, co porządkuje <span>↓</span></a><a class="text-link" href="<?php echo esc_url(home_url('/usprawnienia-firmy#film')); ?>">Film demonstracyjny <span>↗</span></a></div></section>
<section class="section crm-problem"><div class="shell crm-problem-grid"><div><span class="section-no">KIEDY MA SENS</span><h2>Firma ma zapytania, ale część z nich ginie między telefonem, e-mailem i notatkami.</h2></div><ul class="check-list"><li>nie wiadomo, komu trzeba odpowiedzieć</li><li>wyceny nie mają zaplanowanego przypomnienia</li><li>statusy zleceń są tylko w głowie właściciela</li><li>klienci dzwonią, żeby zapytać o etap</li><li>trudno policzyć, ile zapytań kończy się sprzedażą</li></ul></div></section>
<section class="section shell" id="moduly"><div class="section-head"><div><span class="section-no">TYLKO POTRZEBNE MODUŁY</span><h2>Najpierw prosty porządek. Potem ewentualna rozbudowa.</h2></div><p>Nie sprzedaję wielkiego systemu na zapas. Wybieramy 3–6 elementów, które zdejmują z firmy najwięcej ręcznej pracy.</p></div><div class="crm-module-grid"><?php foreach($modules as $m): ?><article><span><?php echo esc_html($m[0]); ?></span><h3><?php echo esc_html($m[1]); ?></h3><p><?php echo esc_html($m[2]); ?></p></article><?php endforeach; ?></div></section>
<section class="section crm-flow"><div class="shell"><span>FORMULARZ</span><i>→</i><span>NOWY KONTAKT</span><i>→</i><span>WYCENA</span><i>→</i><span>ZLECENIE</span><i>→</i><span>ROZLICZENIE</span></div></section>
<section class="section shell crm-assurance"><div class="section-head"><div><span class="section-no">DANE I DOSTĘP POD KONTROLĄ FIRMY</span><h2>CRM nie zamyka danych w jednym miejscu.</h2></div><p>Firma otrzymuje dostęp do danych oraz możliwość eksportu. Zakres zabezpieczeń i backupu ustalamy przed wdrożeniem.</p></div><div class="crm-assurance-grid"><article><span>01</span><h3>Eksport danych</h3><p>Kontakty i zlecenia można przekazać do pliku CSV lub Excel.</p></article><article><span>02</span><h3>Backup na dysku klienta</h3><p>Za dodatkową opłatą podłączamy automatyczną kopię na dysku Google klienta.</p></article><article><span>03</span><h3>Dostęp dla właściwych osób</h3><p>Logowanie, role i zakres dostępu dobieramy do firmy.</p></article></div></section>
<section class="section crm-mobile"><div class="shell crm-mobile-grid"><div><span class="section-no">W CENIE CRM START</span><h2>Klienci i zlecenia pod ręką — <em>także na telefonie.</em></h2><p>Panel można dodać do ekranu głównego telefonu jak aplikację, bez osobnego pobierania ze sklepu.</p><small>To instalowalna aplikacja webowa PWA.</small></div><div class="crm-phone"><header><b>CRM / DZISIAJ</b><span>9:41</span></header><strong>3 zadania</strong><article><i></i>Oddzwoń: nowe zapytanie</article><article><i></i>Wyślij wycenę</article><article><i></i>Zlecenie: piątek</article><footer>Dodaj do ekranu głównego</footer></div></div></section>
<section class="section shell industry-package"><div><span class="section-no">PUNKT STARTU</span><h2>CRM Start</h2><p>Klienci, zapytania, statusy, terminy, następny krok, eksport danych i mobilny panel PWA.</p></div><div><strong>od 4 900 zł netto</strong><span>zwykle 3–4 tygodnie</span><small>Automatyzacje, SMS, backup i dodatkowe role użytkowników wyceniamy zgodnie z zakresem.</small><a class="button" href="#crm-kontakt">Sprawdź swój proces <b>↗</b></a></div></section>
<section class="section contact-section" id="crm-kontakt"><div class="shell contact-grid"><div><span class="section-no">KRÓTKA ANALIZA</span><h2>Powiedz, gdzie dziś zapisujesz klientów i zlecenia.</h2><p>Wskażę najmniejszy sensowny zakres CRM. Nie musisz znać technologii ani mieć gotowej specyfikacji.</p></div><div><?php zm_render_contact_form(); ?></div></div></section>
</main><?php get_footer(); ?>