<!doctype html>
<html lang="en">
<head>
<meta charset="<?php bloginfo('charset'); ?>">
<meta name="viewport" content="width=device-width,initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class('english-site'); ?>>
<?php wp_body_open(); ?>
<main class="english-site" lang="en">
<header class="site-header">
<nav class="nav shell" aria-label="Main navigation">
<a class="brand" href="<?php echo esc_url(home_url('/en')); ?>" aria-label="Zielona Marka, English home"><span class="brand-signature" role="img" aria-label="Zielona Marka"><img class="brand-apple" src="https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/logo-zielona-marka-transparent-v1.png" alt=""><span class="brand-wordmark"><b>ZIELONA</b><b>MARKA</b><small>STRONY WWW I SYSTEMY DLA FIRM</small></span></span></a>
<div class="nav-links"><a href="#work">Work</a><a href="#offer">Offer</a><a href="#systems">Systems</a><a href="#process">Process</a><a href="#contact">Contact</a></div>
<div class="language-switch"><a href="<?php echo esc_url(home_url('/')); ?>" lang="pl">🇵🇱 <span>PL</span></a><a class="active" href="<?php echo esc_url(home_url('/en')); ?>" lang="en">🇬🇧 <span>EN</span></a></div>
<a class="button button-small" href="#contact">Start a project <span>↗</span></a>
<details class="mobile-menu"><summary>Menu <span>+</span></summary><div><a href="#work">Work</a><a href="#offer">Offer</a><a href="#systems">Systems</a><a href="#process">Process</a><a href="#contact">Contact</a></div></details>
</nav>
</header>
<section class="hero shell english-hero"><div class="eyebrow"><span></span>WEBSITES AND SYSTEMS FOR BUSINESSES</div><h1>Digital places where <em>businesses can grow.</em></h1><p>I design clear, fast and human websites, then add only the tools that genuinely improve your workflow.</p><div class="hero-actions"><a class="button" href="#offer">See the offer <span>↓</span></a><a class="text-link" href="#work">Explore examples <span>↘</span></a></div></section>
<section class="quick-start"><div class="shell quick-start-inner"><div class="quick-start-intro"><span class="section-no">A CLEAR START</span><h2>You do not need technical language to start.</h2></div><div class="quick-start-steps"><article><b>01</b><h3>Tell me about the business</h3><p>A short call or online meeting is enough. We can work remotely throughout Poland.</p></article><article><b>02</b><h3>Get a clear proposal</h3><p>Scope, timetable and price before work begins. The standard payment split is 30% to start and 70% after acceptance and QA, before publication.</p></article><article><b>03</b><h3>Review before launch</h3><p>You see the website, request refinements and receive a QA summary before publication.</p></article></div></div></section>
<section id="offer" class="section offer-section"><div class="shell"><div class="section-head"><div><span class="section-no">SERVICES AND PRICING</span><h2>Choose the result, not the technology.</h2></div><p>Every project begins with a short brief. Prices are starting points for a defined scope and can be adjusted after we understand what the business needs.</p></div><div class="english-offers">
<article><span>WEBSITE</span><h3>ZM Start</h3><b>from PLN 2,490 net</b><p>A focused one-page website for a local business, built to move visitors from Google to a call or enquiry.</p><a href="#contact">Ask about this option ↗</a></article>
<article><span>WEBSITE</span><h3>ZM LeadFlow</h3><b>from PLN 4,490 net</b><p>A website plus a qualifying enquiry form that collects the information needed for a first conversation, quote or booking.</p><a href="#contact">Ask about this option ↗</a></article>
<article><span>WEBSITE</span><h3>ZM Flow AI</h3><b>from PLN 6,900 net</b><p>A website, qualifying form and assistant connected to a simple enquiry workflow for the business.</p><a href="#contact">Ask about this option ↗</a></article>
</div></div></section>
<section class="section included"><div class="shell included-grid"><div><span class="section-no">BUILT FOR REAL USE</span><h2>Fast, clear and ready to be found.</h2></div><ul><li>Responsive design for phone, tablet and desktop</li><li>Clickable contact paths and enquiry form</li><li>Technical SEO foundations and clear page structure</li><li>Privacy and cookie information matched to real features</li><li>Quality assurance (QA) before launch</li><li>Handover and practical update instructions</li></ul></div></section>
<section id="process" class="section shell"><div class="section-head"><div><span class="section-no">HOW WE WORK</span><h2>A calm process from idea to launch.</h2></div><p>There are no surprises hidden behind technical terms. You always know the current stage, what is needed from you and what comes next.</p></div><div class="process"><?php foreach(['Discovery and brief','Structure and content','Design and build','QA and launch','Support after launch'] as $i=>$step): ?><article><b><?php echo str_pad((string)($i+1),2,'0',STR_PAD_LEFT); ?></b><h3><?php echo esc_html($step); ?></h3><p><?php echo $i===3?'Responsive checks, key journeys, links and performance review before go-live.':'A focused, documented step with clear decisions and next actions.'; ?></p></article><?php endforeach; ?></div></section>
<section id="systems" class="section english-systems"><div class="shell"><div class="section-head"><div><span class="section-no">BEYOND THE WEBSITE</span><h2>Small systems that remove everyday friction.</h2></div><p>Not every company needs a large CRM or ERP system. Often a carefully designed, smaller workflow is a more useful and affordable starting point.</p></div><div class="english-system-grid"><article><span>01</span><h3>Enquiry and follow-up flow</h3><p>Forms that send a clear enquiry, confirm receipt and create a practical next step.</p></article><article><span>02</span><h3>Client project area</h3><p>A private status page can show progress, next actions, shared files, approvals and an individual project code.</p></article><article><span>03</span><h3>Operations dashboard</h3><p>Dashboards can bring orders, deadlines, key metrics and process status into one simpler view.</p></article><article><span>04</span><h3>Google visibility foundations</h3><p>Website structure, local business information, Search Console readiness and a Google Business Profile can be planned as one consistent presence.</p></article></div></div></section>
<section id="work" class="section shell"><div class="section-head"><div><span class="section-no">SELECTED CONCEPTS</span><h2>Different industries need different stories.</h2></div><p>Each concept uses a deliberately different visual direction, rather than one template applied everywhere.</p></div><div class="visual-proof-strip english-proof"><a href="<?php echo esc_url(home_url('/demo/bistro-strona')); ?>"><small>HOSPITALITY</small><strong>Bistro Forma</strong><span>Menu, booking journey and atmosphere ↗</span></a><a href="<?php echo esc_url(home_url('/demo/natura-strona')); ?>"><small>WELLNESS</small><strong>Natura Studio</strong><span>Calm presentation and booking path ↗</span></a><a href="<?php echo esc_url(home_url('/demo/dom-strona')); ?>"><small>PROPERTY</small><strong>Dom Dobry</strong><span>Availability, trust and enquiry flow ↗</span></a></div></section>
<section id="contact" class="section contact-section"><div class="shell contact-grid"><div><span class="section-no">LET'S TALK</span><h2>Tell me about your business.</h2><p>We can meet online through Google Meet or work entirely by email and phone. Local meetings are possible around Warsaw; remote collaboration is available across Poland.</p><div class="contact-direct"><a href="tel:+48450458466"><small>MOBILE</small><strong>+48 450 458 466</strong></a><a href="mailto:kontakt@zielona-marka.pl"><small>E-MAIL</small><strong>kontakt@zielona-marka.pl</strong></a></div></div><div class="english-contact-card"><span>SHORT BRIEF</span><h3>Start with the essentials.</h3><p>What does your company do, what should the website help with, and when would you like to launch?</p><a class="button" href="mailto:kontakt@zielona-marka.pl?subject=Website%20enquiry%20from%20zielona-marka.pl">Send an enquiry <span>↗</span></a></div></div></section>
<footer><div class="shell footer-grid"><a class="brand" href="<?php echo esc_url(home_url('/en')); ?>"><span class="brand-signature"><img class="brand-apple" src="https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/logo-zielona-marka-transparent-v1.png" alt=""><span class="brand-wordmark"><b>ZIELONA</b><b>MARKA</b><small>STRONY WWW I SYSTEMY DLA FIRM</small></span></span></a><p>Websites and systems for businesses. Designed in Poland, available remotely.</p><div><a href="<?php echo esc_url(home_url('/')); ?>">Polish version</a><a href="<?php echo esc_url(home_url('/polityka-prywatnosci')); ?>">Privacy</a><a href="https://www.facebook.com/StudioGraficzneZielonaMarka" target="_blank" rel="noreferrer">Facebook ↗</a><a href="https://www.instagram.com/zielona.marka.pl/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="#process">How we work</a></div></div></footer>
</main>
<?php wp_footer(); ?>
</body>
</html>