<?php
get_header();
$steps=[
['01','Brief i cel','Krótka rozmowa, najważniejszy problem i ustalenie zakresu.'],
['02','Struktura i treści','Porządkujemy ofertę oraz decydujemy, co klient ma zrobić na stronie.'],
['03','Jeden kierunek projektu','Otrzymujesz konkretny układ strony i widok mobilny do akceptacji.'],
['04','Wdrożenie','Powstaje działająca strona, formularze, kontakt i uzgodnione funkcje.'],
['05','Testy jakości','Sprawdzam telefon, komputer, linki, formularze, szybkość i podstawy SEO.'],
['06','Odbiór, 70% i publikacja','Po akceptacji i rozliczeniu pozostałych 70% publikuję stronę na serwerze klienta, przekazuję dostępy, instrukcję i 14 dni wsparcia.']
];
$faq=[
['Czy muszę od razu wiedzieć, czego potrzebuje moja firma?','Nie. Wystarczy opisać, co dziś zabiera czas, gdzie klientom trudno się skontaktować albo jakie informacje giną po drodze. Na tej podstawie wspólnie ustalimy, czy pierwszym krokiem ma być strona, formularz, rezerwacja, mały CRM czy tylko poprawa obecnego rozwiązania.'],
['Czy musimy spotykać się osobiście?','Nie. Współpraca może odbywać się przez Google Meet, telefon, e-mail i WhatsApp. Działam lokalnie, ale realizuję projekty zdalnie dla firm z całej Polski.'],
['Czy mogę samodzielnie edytować treść?','Tak, jeśli projekt tego wymaga. Przed startem wybieramy prosty sposób aktualizacji, np. WordPress, albo ustalamy zakres opieki nad stroną.'],
['Ile propozycji projektu otrzymam?','Pracujemy na jednym, dopasowanym kierunku projektu. Dzięki temu zamiast wybierać przypadkowy szablon, poprawiamy rozwiązanie przygotowane dla Twojej firmy.'],
['Ile poprawek obejmuje projekt?','W uzgodnionym zakresie są dwie rundy poprawek. Nowe funkcje, kolejne podstrony lub zmiana kierunku po akceptacji są wyceniane osobno przed rozpoczęciem.'],
['Czy strona będzie widoczna w Google?','Przygotowuję techniczne podstawy: strukturę, opisy, wersję mobilną, szybkość i możliwość zgłoszenia strony do Google. Pomagam też przygotować wizytówkę Google dla firmy lokalnej. Nie obiecuję konkretnej pozycji, ponieważ zależy ona też od konkurencji i dalszych działań.'],
['Ile kosztuje strona internetowa dla małej firmy?','Kompletna, jedna przewijana strona ZM Start zaczyna się od 1 449 zł. Końcowa cena zależy od materiałów, liczby podstron, treści, integracji i funkcji, dlatego przed startem zawsze potwierdzamy zakres.'],
['Czy robisz strony dla firm lokalnych?','Tak. Strona może pokazać obszar działania, najważniejsze usługi, telefon, WhatsApp, mapę oraz prostą drogę do zapytania. Współpracuję także z firmami z całej Polski.'],
['Czy mogę mieć stronę bez WordPressa?','Tak. WordPress dobieramy tylko wtedy, gdy firma chce samodzielnie często zmieniać treści. Prostsza, szybsza strona może działać bez panelu WordPress, a aktualizacje możemy wykonywać w ramach opieki.'],
['Czy stronę można później rozbudować o mały CRM?','Tak. Mały CRM to proste zaplecze dla firmy: porządek w zapytaniach, statusach zleceń, klientach i najważniejszych liczbach. Zaczynamy od funkcji, które naprawdę oszczędzają czas, zamiast budować rozbudowany system na zapas.'],
['Co oznacza kontrola jakości (QA)?','QA to skrót od angielskiego Quality Assurance, czyli kontroli jakości. Sprawdzam telefon, komputer, formularze, linki, szybkość, podstawową dostępność oraz pełną ścieżkę klienta.'],
['Co dzieje się po publikacji?','Przekazuję uzgodnione dostępy, instrukcję i 14 dni podstawowego wsparcia startowego. Dalsza opieka jest opcjonalna.'],
['Jak wygląda płatność 30/70?','30% zaliczki po akceptacji zakresu i umowy rezerwuje termin i rozpoczyna pracę. Pozostałe 70% jest płatne po akceptacji gotowej wersji i kontroli jakości (QA), przed publikacją na domenie lub serwerze klienta.'],
['Kto jest właścicielem domeny i strony?','Domena, konto hostingu, konto płatności i inne konta powinny należeć do klienta. Po rozliczeniu klient otrzymuje uzgodniony efekt pracy oraz dostępy.']
];
$tools=[
['01 / FRONT-END','To, co widzi klient','HTML, CSS, JavaScript, TypeScript i React odpowiadają za czytelną, szybką stronę, wygodny formularz i działanie na telefonie.'],
['02 / BACK-END','To, co działa w tle','NestJS, Java, PHP, API i webhooki pozwalają przekazywać zgłoszenia, łączyć usługi i uruchamiać logikę po wysłaniu formularza.'],
['03 / REZERWACJE','Wizyta bez chaosu','Booksy, kalendarz i formularz terminu pomagają prowadzić klienta do rezerwacji bez budowania drugiego systemu na siłę.'],
['04 / PŁATNOŚCI','Bezpieczne zakupy','WooCommerce, Shopify, Przelewy24, Tpay i Stripe pozwalają przyjąć płatność za produkt, voucher lub prostą usługę. Konto u operatora zawsze należy do klienta.'],
['05 / AUTOMATYZACJE','Mniej pracy ręcznej','Python, n8n, Make i Power Automate pomagają przekazywać dane, wysyłać przypomnienia i aktualizować statusy bez przepisywania informacji.'],
['06 / DANE','Porządek i raporty','Zaawansowany Excel, Google Sheets, Looker Studio i Power BI pokazują terminy, koszty i najważniejsze liczby firmy na jednym ekranie.'],
['07 / MAŁY CRM','Zapytania nie giną','SQL, Cloudflare D1, Airtable i bezpieczne API porządkują klientów, zlecenia, statusy i następne działania w jednym miejscu.'],
['08 / PANEL KLIENTA','Mniej pytań o status','Widok mobilny, bezpieczny kod dostępu i PWA pozwalają klientowi sprawdzić etap, termin oraz dokumenty bez kolejnego telefonu.'],
['09 / WORDPRESS','Edycja bez dotykania kodu','WordPress, Gutenberg, motyw blokowy, PHP, MySQL, pola własne i REST API pozwalają samodzielnie edytować stronę, a jednocześnie tworzyć indywidualne szablony, realizacje, formularze oraz integracje.'],
['10 / KONTROLA','Gotowe do startu','Kontrola jakości (QA, ang. Quality Assurance), Lighthouse, Google Search Console i GA4 pomagają sprawdzić stronę oraz zobaczyć, skąd przychodzą zapytania.']
];
$tech=[
['01','Informacje dla Google','Każda ważna podstrona dostaje własny tytuł, opis i właściwy adres. Dzięki temu wyszukiwarka lepiej rozumie, czego dotyczy strona.'],
['02','Jedna właściwa wersja adresu','Ustawiam główny adres strony, aby nie powstawały kopie pod różnymi wariantami domeny.'],
['03','Obrazek przy udostępnianiu','Przygotowuję grafikę i opis, które pokazują się po wklejeniu linku na Facebooku, w Messengerze czy SMS-ie.'],
['04','Mapa strony i kontrola dostępu','Strona otrzymuje mapę dla wyszukiwarek. Prywatne zaplecze i wersje demonstracyjne są oznaczone tak, aby nie trafiały do wyników Google.']
];
?>
<main class="zm-public">
<section class="page-hero shell"><span class="eyebrow"><i></i>JAK PRACUJĘ</span><h1>Jasne decyzje od pierwszej rozmowy <em>do działającej strony.</em></h1><p>Nie musisz prowadzić projektu technicznie. Wiesz, czego potrzebuję od Ciebie, co robię na danym etapie i kiedy podejmujemy decyzję.</p><a class="button" href="<?php echo esc_url(home_url('/kontakt')); ?>">Zacznij od briefu <span>↗</span></a></section>
<section class="section shell"><div class="section-head"><div><span class="section-no">PROCES</span><h2>Od pomysłu do publikacji.</h2></div><p>Mała, podstawowa strona: od 72 godzin do 14 dni od otrzymania kompletu materiałów i ustalenia zakresu. Rozbudowane strony, sklepy i systemy mają terminy ustalane osobno.</p></div><div class="timeline"><?php foreach($steps as $s): ?><article><span><?php echo esc_html($s[0]); ?></span><h3><?php echo esc_html($s[1]); ?></h3><p><?php echo esc_html($s[2]); ?></p></article><?php endforeach; ?></div></section>
<section class="section meeting-section"><div class="shell meeting-grid"><div><span class="section-no">SPOTKANIE ONLINE I PRZYGOTOWANIE PROJEKTU</span><h2>Jedna rozmowa może uporządkować cały kierunek.</h2><p>Możemy spotkać się przez Google Meet. Na ekranie pokazuję pierwszy układ strony, najważniejsze kroki klienta i elementy, które mają odciążyć Twoją firmę.</p><p>Po spotkaniu otrzymujesz prosty plan: co przygotowujemy, co jest pierwszym etapem i jaki będzie następny krok.</p><a class="button" href="<?php echo esc_url(home_url('/kontakt')); ?>">Umów krótką rozmowę <span>↗</span></a></div><figure class="meeting-visual"><img src="https://www.zielona-marka.pl/lukasz-zielona-marka-jak-pracuje-20260908.webp" width="1672" height="941" alt="Łukasz pracujący nad stroną internetową i kodem" loading="lazy"><figcaption>Projektowanie strony, sprawdzanie widoku i praca nad kodem.</figcaption></figure></div></section>
<section class="section qa-section"><div class="shell qa-grid"><div><span class="section-no">KONTROLA JAKOŚCI / QA</span><h2>Strona jest testowana, zanim zacznie pracować na Twoją firmę.</h2><p class="spaced-copy">Kontrola jakości (<b>QA</b>, ang. <i>Quality Assurance</i>) oznacza ostatnie sprawdzenie strony przed publikacją. Na koniec otrzymujesz proste podsumowanie: co zostało sprawdzone i co jest gotowe do startu.</p><div class="zm-quality-mark" aria-label="QA, standard kontroli jakości Zielonej Marki"><span>STANDARD<br>ZIELONEJ MARKI</span><strong>✓ QA</strong><small>KONTROLA JAKOŚCI<br>PRZED PUBLIKACJĄ</small></div></div><div><ul class="check-list"><li>telefon, tablet i komputer</li><li>formularze, e-mail, numer telefonu i WhatsApp</li><li>linki, przekierowania i podstawowe błędy</li><li>szybkość oraz stabilność</li><li>przygotowanie do Google i mapa strony</li><li>podstawowa dostępność oraz czytelność</li></ul><p><b>Lighthouse</b> to test Google sprawdzający m.in. szybkość, dostępność i techniczną jakość strony. Jest narzędziem kontroli, a nie gwarancją pozycji w wyszukiwarce.</p><a class="text-link" href="<?php echo esc_url(home_url('/raport-qa')); ?>">Zobacz przykładowy raport kontroli jakości <span>↗</span></a></div></div></section>
<section class="section technology-section"><div class="shell"><div class="section-head"><div><span class="section-no">NARZĘDZIA DOBIERAM DO CELU</span><h2>Klient nie musi znać technologii, żeby dostać dobre rozwiązanie.</h2></div><p>Najpierw ustalamy, co ma zmienić się w firmie. Dopiero potem wybieram sposób wykonania strony, formularza, automatyzacji lub prostego zaplecza.</p></div><div class="technology-grid"><?php foreach($tools as $x): ?><article><span><?php echo esc_html($x[0]); ?></span><h3><?php echo esc_html($x[1]); ?></h3><p><?php echo esc_html($x[2]); ?></p></article><?php endforeach; ?></div></div></section>
<section class="section shell technical-checks"><div class="section-head"><div><span class="section-no">CO SPRAWDZAM PRZED PUBLIKACJĄ</span><h2>Techniczne sprawy bez technicznego języka.</h2></div><p>To elementy, które pomagają stronie być czytelną dla ludzi, Google i urządzeń mobilnych.</p></div><div class="technical-check-grid"><?php foreach($tech as $x): ?><article><span><?php echo esc_html($x[0]); ?></span><h3><?php echo esc_html($x[1]); ?></h3><p><?php echo esc_html($x[2]); ?></p></article><?php endforeach; ?></div></section>
<section class="section shell seo-grid"><div><span class="section-no">GOTOWA DO DALSZEGO SEO</span><h2>Po starcie nie trzeba naprawiać podstaw.</h2></div><div><p>Strona otrzymuje logiczną strukturę, poprawne adresy, tytuły i opisy, mapę strony, wersję mobilną, szybkie działanie i możliwość podłączenia narzędzi Google.</p><p>Widoczność w Google rozwija się później przez treści, lokalną wiarygodność, opinie i dalsze działania. Uczciwie nie gwarantuję konkretnej pozycji.</p></div></section>
<section class="section rules-section"><div class="shell rules-grid"><article><span>30%</span><h3>Zaliczka na start</h3><p>Po akceptacji zakresu i umowy rezerwuję termin oraz rozpoczynam pracę.</p></article><article><span>70%</span><h3>Przed publikacją</h3><p>Po odbiorze gotowej wersji i kontroli jakości (QA), przed publikacją na serwerze klienta.</p></article><article><span>02</span><h3>Dwie rundy poprawek</h3><p>Uwagi zbieramy i wprowadzamy w jasno określonym zakresie.</p></article><article><span>14</span><h3>Dni wsparcia startowego</h3><p>Po publikacji pomagam spokojnie przejść przez pierwsze dni działania strony.</p></article></div></section>
<section class="section shell faq-page"><div class="section-head"><div><span class="section-no">FAQ</span><h2>Najważniejsze odpowiedzi przed startem.</h2></div><p>Krótko, konkretnie i bez technicznego żargonu.</p></div><div class="faq-list"><?php foreach($faq as $i=>$q): ?><details<?php echo $i===0?' open':''; ?>><summary><span><?php echo esc_html(sprintf('%02d',$i+1)); ?></span><?php echo esc_html($q[0]); ?><i>+</i></summary><p><?php echo esc_html($q[1]); ?></p></details><?php endforeach; ?></div></section>
</main><?php get_footer(); ?>