<?php
if (!isset($industry) || !isset($config)) { return; }
?><!doctype html>
<html <?php language_attributes(); ?>>
<head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class('industry-demo industry-'.$industry); ?>><?php wp_body_open(); ?>
<main class="industry-demo industry-<?php echo esc_attr($industry); ?>" data-industry-demo data-industry="<?php echo esc_attr($industry); ?>">
<header><a class="brand" href="<?php echo esc_url(home_url('/')); ?>"><span class="brand-signature compact"><img class="brand-apple" src="https://raw.githubusercontent.com/lukaszst-cz/zielona-marka-pl/main/public/logo-zielona-marka-transparent-v1.png" alt=""><span class="brand-wordmark"><b>ZIELONA</b><b>MARKA</b><small>STRONY WWW I SYSTEMY DLA FIRM</small></span></span></a><span class="demo-badge">DEMO PROCESOWE · DANE PRZYKŁADOWE</span><a href="<?php echo esc_url(home_url('/#kontakt')); ?>">Zapytaj o takie zaplecze ↗</a></header>
<div class="industry-shell">
<section class="industry-title"><div><span class="section-no"><?php echo esc_html(strtoupper($config['brand']).' / '.$config['label']); ?></span><h1><?php echo esc_html($config['title']); ?></h1><p>Interaktywny przykład tego, co właściciel i zespół mogą widzieć po zalogowaniu.</p></div><button type="button" data-demo-add>+ Zasymuluj dane z formularza</button></section>
<section class="transport-kpis"><?php foreach($config['kpi'] as $i=>$name): ?><article><span><?php echo esc_html($name); ?></span><b data-demo-stat="<?php echo (int)$i; ?>"><?php echo $i===0?count($config['rows']):($i===1?'50%':($i===2?'0 zł':'0')); ?></b><small>wartość demonstracyjna</small></article><?php endforeach; ?></section>
<section class="industry-grid"><div class="transport-card"><div class="transport-head"><div><span class="section-no">BIEŻĄCA PRACA</span><h2><?php echo esc_html($config['work_title']); ?></h2></div><small>Zmień etap i obserwuj automat</small></div><div data-demo-rows>
<?php foreach($config['rows'] as $row): ?><article class="industry-row" data-demo-row data-id="<?php echo esc_attr($row['id']); ?>" data-stage="<?php echo (int)$row['stage']; ?>" data-value="<?php echo (int)$row['value']; ?>"><div><b><?php echo esc_html($row['time']); ?></b><small><?php echo esc_html($row['id']); ?></small></div><div><strong><?php echo esc_html($row['name']); ?></strong><small><?php echo esc_html($row['detail']); ?></small></div><span data-stage-label><?php echo esc_html($config['stages'][$row['stage']]); ?></span><div><i data-stage-bar style="width:<?php echo esc_attr((($row['stage']+1)/count($config['stages']))*100); ?>%"></i></div><button type="button" data-demo-advance><?php echo $row['stage']===count($config['stages'])-1?'Gotowe':'Następny etap →'; ?></button></article><?php endforeach; ?>
</div></div>
<aside class="transport-card"><div class="transport-head"><div><span class="section-no">AUTOMATYZACJE</span><h2>Dziennik działania</h2></div></div><div class="automation-log" data-demo-log><p><i></i> <?php echo esc_html($config['automation']); ?></p><p><i></i> Dashboard KPI został przeliczony</p><p><i></i> Lista zadań zespołu jest aktualna</p></div><div class="automation-note"><b>Pełna wersja wdrożeniowa</b><span>Role użytkowników, prawdziwa baza danych, integracje, kopie, eksporty, instrukcja i testy QA. Zakres zawsze dobierany jest do realnego procesu firmy.</span></div></aside></section>
<section class="process-blueprint"><div><span class="section-no">MAPA PROCESU</span><h2>Od wejścia klienta do wyniku i KPI.</h2></div><div><?php foreach($config['stages'] as $i=>$stage): ?><article><b><?php echo str_pad((string)($i+1),2,'0',STR_PAD_LEFT); ?></b><span><?php echo esc_html($stage); ?></span><?php if($i<count($config['stages'])-1): ?><i>→</i><?php endif; ?></article><?php endforeach; ?></div></section>
</div></main>
<script type="application/json" data-demo-config><?php echo wp_json_encode(['stages'=>$config['stages'],'newName'=>$config['new_name'],'newValue'=>$config['new_value']], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); ?></script>
<?php wp_footer(); ?></body></html>